ByConity/ByConity

README.md

Changes:
typo fix build command line in README.md

[Doc] typo fix build command line in README.md

---

README.md
docker/byconity/.env
docker/byconity/README.md
docker/byconity/docker-compose.yml
docker/byconity/fdb/fdb.cluster
docker/byconity/hdfs/core-site.xml
docker/byconity/hdfs/create_users.sh
docker/byconity/hdfs/hdfs-site.xml
docker/byconity/hdfs/log4j.properties
docker/byconity/simple/daemon-manager.yml
docker/byconity/simple/server.yml
docker/byconity/simple/tso.yml
docker/byconity/simple/users.yml
docker/byconity/simple/worker.yml

Add local development with docker guide

---

docker/byconity/README.md
docker/byconity/docker-compose.yml.multiworkers
docker/byconity/multi-workers/daemon-manager.yml
docker/byconity/multi-workers/resource-manager.yml
docker/byconity/multi-workers/server.yml
docker/byconity/multi-workers/tso.yml
docker/byconity/multi-workers/users.yml
docker/byconity/multi-workers/worker.yml

Add multi-workers local cluster

---

README.md

- minor change on local development document
...
...

[Doc] minor changes for ByConity local deployment

---

docker/byconity/README.md

add create hdfs users for ByConity local deployment

---

docker/executable_wrapper/run.sh

- New Feature
- Bug Fix
- Improvement
- Other
...
...

add check for unconfig

---

doc/project_structure.md

- simple src structure des
...
...

add simple description for src structure

---

src/CloudServices/selectPartsToMerge.cpp
src/Storages/MergeTree/KeyCondition.cpp
src/Storages/MergeTree/KeyCondition.h
src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp
src/Storages/MergeTree/MergeTreeSettings.h

- Performance optimization for key condition analysis. Can run binary search if lhs is wrapped by monotonic functions
...

Performance optimization for key condition analysis

---

docker/executable_wrapper/Makefile
docker/executable_wrapper/run.sh

- New Feature
- Bug Fix
- Improvement
- Other
...
...

update docker repo

---

deploy/deploy.py

change users.xml to correct target

---

docs/zh-cn/SQL语法说明/sql-statements.mdx
docs/zh-cn/基础使用手册/设计库表.mdx

I hereby agree to the terms of the CLA available at: [ByConity]
...

update order_by key cannot rename

---

src/Interpreters/InterpreterAlterWarehouseQuery.cpp
src/Interpreters/InterpreterCreateWarehouseQuery.cpp
src/Interpreters/InterpreterCreateWorkerGroupQuery.cpp
src/Interpreters/InterpreterDropWarehouseQuery.cpp
src/Interpreters/InterpreterDropWorkerGroupQuery.cpp

fix coredump when executing VW DDL but RM is not enabled

---

packages/README.md

- New Feature
- Bug Fix
- Improvement
- Other
...
...

Update guideline doc

---

src/Storages/System/StorageSystemMetastore.cpp
src/Storages/System/attachSystemTables.cpp

- Bug Fix
...
fix 2 cores:
https://github.com/ByConity/ByConity/issues/29
https://github.com/ByConity/ByConity/issues/32
...

Core fix for querying system tables

---

src/Interpreters/executeQuery.cpp

- Bug Fix
...
- Txn leaked for a reported [issue](https://github.com/ByConity/ByConity/issues/63), from long term, we should consider RAII way to avoid potential leaking.
...

fix txn leak when exception happening

---

src/CloudServices/CnchMergeMutateThread.cpp

Fix getting worker client

---

src/Common/HostWithPorts.cpp
src/Common/HostWithPorts.h
src/Interpreters/CnchQueryMetrics/QueryMetricLogHelper.cpp
src/Interpreters/Context.cpp
src/ResourceManagement/ResourceReporter.cpp
src/ResourceManagement/ResourceReporter.h

- New Feature
- Bug Fix
- Improvement
- Other
...
...

support get worker id info from config

---

packages/README.md
packages/byconity-resource-manager.postinstall
packages/byconity-resource-manager.service
packages/byconity-resource-manager.yaml
programs/server/CMakeLists.txt
programs/server/byconity-resource-manager.xml
programs/server/byconity-worker-write.xml
programs/server/byconity-worker.xml
programs/server/cnch_config.xml
src/Common/HostWithPorts.cpp

- New Feature
- Bug Fix
- Improvement
- Other
...
...

add RM package

---

src/Core/Settings.h

...
Pros:
- less txn lookup overhead
- less schedule overhead
- fix 01497_attach_with_delta ci case temporarily 
Cons
- Insert has extra post commit overhead 
...

make post commit sync

---

src/Catalog/Catalog.cpp
src/Catalog/FDBClient.cpp
src/Catalog/FDBClient.h
src/Catalog/IMetastore.h
src/Catalog/MetastoreCommon.h
src/Catalog/MetastoreFDBImpl.cpp
src/Catalog/MetastoreFDBImpl.h
src/Catalog/MetastoreProxy.cpp
src/Catalog/tests/metastore_benchmark.cpp

Improve CAS operation

---

src/Processors/tests/gtest_exchange_trans.cpp

bugfix for #174, fix unstable unit test for RemoteSenderLimitTest

---

src/Interpreters/InterpreterCreateQuery.cpp
src/Protos/DataModelHelpers.cpp
src/Protos/data_models.proto
src/Storages/HDFS/HDFSCommon.cpp
src/Storages/HDFS/HDFSCommon.h
src/Storages/HDFS/ReadBufferFromByteHDFS.cpp
src/Storages/Hive/HiveDataPart.cpp
src/Storages/Hive/HiveDataPart.h
src/Storages/Hive/HiveMetastore.cpp
src/Storages/Hive/HiveMetastore.h
src/Storages/Hive/HivePartition.cpp
src/Storages/Hive/HivePartition.h
src/Storages/StorageCnchHive.cpp
src/Storages/StorageCnchHive.h

- Improvement
fix #132 
...
...

Support hive table on external Hdfs

---

src/CloudServices/CnchPartGCThread.cpp

- Bug Fix
directly remove part from catalog if part don't exists on disk
When the user executes the detach partition, part will be moved to the detach directory, and then GCThread will find that part no longer exists on disk when executed. At this time, it will throw an exception and prevent part from being deleted from the catalog

directly remove part from catalog if part don't exists on disk

---

src/DaemonManager/DaemonJobServerBGThread.cpp

- Bug Fix
Fix bug happen in CI

minor fix DaemonManager logic

---

src/CloudServices/CloudMergeTreeDedupWorker.cpp
src/Storages/MergeTree/CloudMergeTreeBlockOutputStream.cpp
src/Storages/StorageCnchMergeTree.cpp
src/Transaction/CnchLock.cpp
src/Transaction/CnchLock.h
src/WorkerTasks/CloudUniqueMergeTreeMergeTask.cpp

fix tryLock

---

src/Storages/MergeTree/MergeTreeCNCHDataDumper.h

According to the code, the data content includes the `unique key index`.

minor comment change

---

README.md
Testing.md
ci_scripts/run_ci_in_development_env.sh

Add testing guide line document

add testing guideline

---

src/Core/Settings.h

Enable input_format_parallel_parsing fix #217

---

src/Processors/Executors/PullingAsyncPipelineExecutor.cpp
src/Statistics/SubqueryHelper.cpp

- Bug Fix
- try fix https://github.com/ByConity/ByConity/issues/214

try throw correct exception for creating stats

---

programs/client/Client.cpp
programs/server/Server.cpp
src/Interpreters/Context.cpp

fix hdfs config

---

src/Storages/MergeTree/MergeTreeIndexReader.cpp
tests/queries/4_cnch_stateless/00974_adaptive_granularity_secondary_index.sql

- Bug Fix
- Fix mark count missmatch during loading index
Close #228

Fix mark count missmatch during loading index

---

programs/server/Server.cpp

Bug Fix
fix issue #235 - fix ipv6 issue when enable optimizer setting

fix rpc service use ipv6 

---

programs/server/Server.cpp

- Bug Fix
link to issue.   https://github.com/ByConity/ByConity/issues/235 
...

fix rpc service use ipv6

---

tests/clickhouse-test

Remove debug print in clickhouse-test

---

.github/workflows/ci.yml
ci_scripts/config/server.xml
ci_scripts/config/worker-write.xml
ci_scripts/config/worker.xml
docker/test/certificate/load_certificate_tables.py

- Testing Improvement
Add certificate test suite

feat: add certificate test suite

---

src/AggregateFunctions/AggregateFunctionUniqCombined.h
src/Columns/ReverseIndex.h
src/Common/HashTable/ClearableHashMap.h
src/Common/HashTable/ClearableHashSet.h
src/Common/HashTable/HashMap.h
src/Common/HashTable/HashSet.h
src/Common/HashTable/HashTable.h
src/Common/HashTable/LRUHashMap.h
src/Common/HashTable/StringHashTable.h
src/Common/HashTable/TwoLevelHashTable.h
src/Common/tests/gtest_hash_table.cpp
tests/performance/cache_values_inside_hash_table_grower.xml

- Improvement
- pick https://github.com/ClickHouse/ClickHouse/pull/38413 
...

[Perf] Precalculate values inside HashTableGrower

---

programs/server/byconity-server.xml
programs/server/byconity-worker.xml

fix: update config file to support ipv6

---

src/Catalog/FDBClient.cpp

- Improvement
Currently transaction to FDB block indefinitely until receive result from fdb server.
This causing hang to application in case fdb server has issue. This PR is to add timeout for it. 
The below picture show snapshot of timeout fdb request

feat: add timeout for FoundationDB transactions

---

src/Interpreters/InterpreterFactory.cpp

- Bug Fix
- The insert select is not supported for optimizer.  Disable it explicitly.

Explicitly disable optimizer for insert select

---

README.md

doc: remove outdated content

---

utils/release-note/release_note.py

chore: Added the first version of release_note generation script

---

programs/server/Server.cpp

fix: fix listen_try logic on brpc

---

README.md

Links to Twitter and youtube added.

Twitter and Youtube added to ReadMe

---

src/Functions/FunctionsConversion.h

Below commit from `cnch-ce-merge` is cherry-picked:
```
commit 1a5f04039a2d8a75b1249838230287d4d7567b11
Date:   Thu Feb 9 15:22:14 2023 +0800
add annotations for FunctionsConversion
```

add annotations for FunctionsConversion

---

src/Columns/ColumnArray.cpp
src/Core/MySQL/MySQLReplication.cpp
src/Interpreters/ClusterProxy/SelectStreamFactory.cpp
src/Processors/Formats/Impl/TSKVRowInputFormat.cpp
src/QueryPlan/IQueryPlanStep.cpp
src/Storages/IndexFile/Status.h
src/Storages/MergeTree/MergeTreeIndexConditionBloomFilter.cpp
src/Storages/MergeTree/MergeTreeIndexFullText.cpp
src/Storages/MergeTree/MergeTreeReaderCNCH.cpp
src/Storages/MergeTree/ReplicatedMergeTreeQueue.h

cp: 7220cb8

---

src/DaemonManager/DaemonManager.cpp
src/ResourceManagement/ResourceManager.cpp
src/TSO/TSOServer.cpp

- Bug Fix
Fix #328 
Currently TSO, DM, RM component default listens on interface `::` which maybe be able to work in some OS/machine. So this fix will allow to specify which intefaces the component want to listen to.

fix: support listen_host and listen try for TSO, DM, RM

---

CONTRIBUTING.md

Created a new contributor guide that has more detail and is easier to follow.

New Contributor Guide and updates

---

docker/packager/binary/Dockerfile

fix: Update Dockerfile

---

docker/builder/README.md
docker/builder/centos/Dockerfile
docker/builder/centos/Makefile
docker/builder/centos/build.sh

- Build Improvement
Add docker build image for CentOS

feat: add docker image build for centos

---

src/DataStreams/TransactionWrapperBlockInputStream.cpp
src/DataStreams/TransactionWrapperBlockInputStream.h
src/Interpreters/InterpreterInsertQuery.cpp
src/MergeTreeCommon/CnchStorageCommon.cpp
src/MergeTreeCommon/CnchStorageCommon.h
src/Storages/IngestColumnCnch/IngestColumnCnch.cpp
src/Storages/StorageCnchMergeTree.cpp
src/Storages/StorageCnchMergeTree.h

- Bug Fix
Currently insert select or insert in file doesn't show progress and unable to canceled. This PR will fix it

fix: fix forward query to worker

---

src/CloudServices/CnchMergeMutateThread.cpp
src/CloudServices/CnchPartGCThread.cpp
src/CloudServices/DedupWorkerManager.h
src/CloudServices/ReclusteringManagerThread.cpp
src/CloudServices/ReclusteringManagerThread.h
src/Core/Settings.h
src/Interpreters/ClusterProxy/SelectStreamFactory.cpp
src/Interpreters/Context.cpp
src/Interpreters/Context.h
src/Interpreters/InterpreterSystemQuery.cpp
src/Parsers/ASTSystemQuery.cpp
src/Parsers/ASTSystemQuery.h
src/Parsers/ParserSystemQuery.cpp
src/Processors/Sources/RemoteSource.cpp
src/Processors/Sources/RemoteSource.h
src/Storages/MergeTree/MergeTreeSettings.h
src/Storages/StorageCnchMergeTree.cpp

* cherry-pick
* feat: add settings resize_number_after_remote_source to resize after remote source
* feat: cherry pick `Add ability to pause/resume clustering task`
* refactor: [cp] enhance gc bitmaps

cp: b0f5b59, 0a5c7fe, 76be17e

---

src/CloudServices/CnchMergeMutateThread.cpp
src/CloudServices/CnchPartGCThread.cpp
src/CloudServices/ReclusteringManagerThread.cpp
src/CloudServices/ReclusteringManagerThread.h
src/Core/Settings.h
src/Interpreters/ClusterProxy/SelectStreamFactory.cpp
src/Interpreters/Context.cpp
src/Interpreters/Context.h
src/Interpreters/InterpreterSystemQuery.cpp
src/Parsers/ASTSystemQuery.cpp
src/Parsers/ASTSystemQuery.h
src/Parsers/ParserSystemQuery.cpp
src/Processors/Sources/RemoteSource.cpp
src/Processors/Sources/RemoteSource.h
src/Storages/MergeTree/MergeTreeSettings.h
src/Storages/StorageCnchMergeTree.cpp

Revert "cp: b0f5b59, 0a5c7fe, 76be17e"

---

tests/queries/4_cnch_stateless/00987_alter_ingest_partition_memory_efficient_map_type2.sql
tests/queries/4_cnch_stateless/00988_alter_ingest_partition_memory_efficient2.sql

- Bug Fix
Fix unstable test case

fix: fix unstable test case

---

src/CloudServices/CnchPartGCThread.cpp
src/Core/Settings.h
src/Interpreters/ClusterProxy/SelectStreamFactory.cpp
src/Parsers/ASTSystemQuery.cpp
src/Processors/Sources/RemoteSource.cpp
src/Processors/Sources/RemoteSource.h
src/Storages/MergeTree/MergeTreeSettings.h
src/Storages/StorageCnchMergeTree.cpp

* cherry-pick
* feat: add settings resize_number_after_remote_source to resize after remote source
* refactor: [cp] enhance gc bitmaps

Repick: b0f5b59, 76be17e

---

.github/workflows/ci.yml
programs/server/Server.cpp
src/Interpreters/Context.cpp
src/Interpreters/Context.h

- Bug Fix
Failed to get exchange port causing server unable to start up

fix: fix failed to get exchange port

---

docker/executable_wrapper/Makefile

- Bug Fix
Fix executable wrapper script

fix: fix executable wrapper script

---

src/DataTypes/MapHelpers.cpp
src/DataTypes/MapHelpers.h
src/Storages/MergeTree/IMergeTreeDataPart.cpp
src/Storages/MergeTree/MergeTreeSequentialSource.cpp
src/WorkerTasks/MergeTreeDataMerger.cpp

- Bug Fix
2 issues to fix in this pr
- fix empty result for map column after merging
- close https://github.com/ByConity/ByConity/issues/379

fix merge issue for map column

---

src/Common/ZooKeeper/ZooKeeper.cpp
src/Common/ZooKeeper/ZooKeeper.h
src/Core/Settings.h
src/Interpreters/Context.cpp
src/Interpreters/Context.h
src/Interpreters/DistributedStages/PlanSegment.cpp
src/Interpreters/DistributedStages/PlanSegment.h
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Interpreters/DistributedStages/PlanSegmentExecutor.h
src/Interpreters/QueryLog.cpp
src/Interpreters/QueryLog.h
src/Interpreters/executeQuery.cpp
src/Storages/MergeTree/CnchAttachProcessor.cpp
src/Storages/StorageCnchMergeTree.cpp
src/Storages/StorageCnchMergeTree.h

* cherry-pick
* fix: start new zookeeper session from new endpoints
* feat: record segment query log on worker
* fix: Complete the full support of positional arguments
* fix: [cp] clear merge tasks before creating drop range

cp: 034a7f0, 9c73bf5, d78647f, 3c310ac

---

src/Storages/Hive/HiveMetastore.cpp

fix hive metastore client bug

---

.github/workflows/ci.yml
tests/queries/0_stateless/45015_explain_stats.sql
tests/queries/0_stateless/45015_explain_stats_lowcard.sql
tests/queries/0_stateless/45015_explain_stats_lowcard_nullable.sql
tests/queries/0_stateless/45015_explain_stats_nullable.sql
tests/queries/4_cnch_stateless/40019_name_resolution_in_order_by.sql
tests/queries/4_cnch_stateless/40025_function_as_correlate_filter.sql
tests/queries/4_cnch_stateless/40033_aliases_visibility_scope.sql
tests/queries/4_cnch_stateless/40034_opt_arrayjoin_limit_issue.reference
tests/queries/4_cnch_stateless/48015_scalar_subquery.sql
tests/queries/7_clickhouse_sql/00392_enum_nested_alter.sql

CI
* disable whilte list in ci

fix: move setings to CI

---

doc/system_table.md

doc: add document for system tables

---

doc/system_table.md

- Documentation
Fix document for system table

doc: fix document for system table

---

doc/system_table.md

- Documentation
Fix document for system table

fix: fix document

---

README.md

Currently, using client version `7.1.0` will lead to "'fdb_c_types.h' file not found" error.
This issue has been confirmed to be fixed in `7.1.3`. See https://github.com/apple/foundationdb/issues/6822 for more details.

docs(readme): update minimal foundationdb client library version.

---

src/Storages/DiskCache/IDiskCache.cpp

* cherry-pick
* fix: fix uninitialized member

cp: f955211

---

docker/executable_wrapper/Makefile
docker/executable_wrapper/README.md
docker/executable_wrapper/config/cnch_config.xml
docker/executable_wrapper/config/rm.xml
docker/executable_wrapper/config/worker-write.xml
docker/executable_wrapper/config/worker.xml
docker/executable_wrapper/run.sh

- Bug Fix
add resource manager component for executable wrapper

fix: add rm for executable wrapper

---

src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp

bug fix
fix https://github.com/ByConity/ByConity/issues/518

fix s3 support projection

---

.clang-format

- Improvement
deleted duplicate line 77 in .clang-format file which said: ``` IndentWidth: 4```
...

#584 Issue: Update .clang-format

---

src/Common/ThreadStatus.h
src/Dictionaries/ClickHouseDictionarySource.cpp
src/Dictionaries/ClickHouseDictionarySource.h
src/Parsers/formatTenantDatabaseName.cpp
src/Parsers/formatTenantDatabaseName.h
tests/queries/4_cnch_stateless/11008_no_ip_port_dictionary.reference
tests/queries/4_cnch_stateless/11008_no_ip_port_dictionary.sql

- Bug Fix
Cherry-pick from internal branch

fix: fix dictionary failed to update and tenant id

---

src/Interpreters/CnchSystemLog.cpp
src/Interpreters/SegmentScheduler.cpp
src/Interpreters/executeQuery.cpp
src/Server/GRPCServer.cpp
src/Server/TCPHandler.cpp
src/TSO/TSOServer.cpp

* Cherry-pick
* fix: Fix a bug related to query_metrics and query_worker_metrics
* fix: use toStaryOfDay as query_metrics default ttl expression like 1.4
* fix: add more tso logs
* feat: refine mpp query mode error report for all protocol

Daily Cherry-pick from the internal_20230808_174541

---

README.md
doc/build_in_metal_machine.md
docker/builder/Makefile
docker/builder/centos/Makefile
docker/executable_wrapper/run.sh
docker/packager/README.md

doc: update package guide

---

src/Interpreters/Context.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/SegmentScheduler.cpp
src/Interpreters/SegmentScheduler.h
src/Interpreters/executeQuery.cpp

* Cherry-pick
* Remove duplicated codes, rename var name, add lock for potential multithread access
* fix compiler warning

Daily Cherry-pick from the internal_20230817_163252

---

CONTRIBUTING.md
contrib/pdqsort/pdqsort.h
src/CMakeLists.txt
src/Functions/least.cpp
tests/testflows/rbac/requirements/requirements.md
tests/testflows/rbac/requirements/requirements.py

- New Feature
- Bug Fix
- Improvement
- Other
...

fix some typo

---

src/Core/Settings.h

- Improvement
-  optimize_skip_unused_shards is helpful to prune parts with unrelated bucket
-  close https://github.com/ByConity/ByConity/issues/543

enable optimize_skip_unused_shards by default

---

src/Processors/QueryPipeline.cpp

- New Feature
Fix build error in clang-11(Ubuntu 20.4)

Fix build error

---

src/Interpreters/Cache/QueryCache.cpp
tests/queries/4_cnch_stateless/50001_test_query_cache.sql

- Bug Fix
Fix coredump issue and add test case for query cache

fix: fix coredump related to query cache result

---

src/Common/ThreadFuzzer.cpp

- close https://github.com/ByConity/ByConity/issues/480

Fix undefined __pthread_mutex_lock/unlock for glibc

---

src/Interpreters/executeQuery.cpp
src/Interpreters/executeQueryHelper.cpp
src/Interpreters/executeQueryHelper.h
src/Storages/Kafka/StorageCnchKafka.cpp
src/Storages/StorageCnchMergeTree.cpp
src/Storages/StorageMaterializedView.cpp

- Bug Fix
Pick query forwarding fix from internal branch

fix: fix query forwarding

---

src/Catalog/Catalog.cpp
src/CloudServices/CnchCreateQueryHelper.cpp
src/Interpreters/InterpreterCreateQuery.cpp
src/Parsers/ASTCreateQuery.cpp
src/Parsers/ParserCreateQuery.cpp

- Bug Fix
fix hive schema inference bug

fix: fix hive schema inference

---

src/Common/ProfileEvents.cpp

- New Feature
- Bug Fix
- Improvement
- Other
...

Add profile events for RBAC

---

src/Interpreters/executeQueryHelper.cpp
src/Storages/StorageCnchMergeTree.cpp

dry run for analyze

---

src/Analyzers/Analysis.cpp
src/Analyzers/Analysis.h
src/Analyzers/ExprAnalyzer.cpp
src/Core/Settings.h
src/Functions/FunctionsByteMap.cpp
src/Interpreters/InterpreterExplainQuery.cpp
src/Interpreters/InterpreterExplainQuery.h
src/Interpreters/executeQuery.cpp
src/Optimizer/ExpressionRewriter.cpp
src/Optimizer/ExpressionRewriter.h
src/Optimizer/Property/PropertyDeriver.cpp
src/Optimizer/Property/PropertyDeterminer.h
src/Parsers/ASTExplainQuery.h
src/Parsers/ParserExplainQuery.cpp
src/Processors/Exchange/MultiPartitionExchangeSink.cpp
src/Processors/Exchange/MultiPartitionExchangeSink.h
src/Processors/Exchange/RepartitionTransform.cpp
src/Processors/Exchange/RepartitionTransform.h
src/Processors/tests/gtest_exchange_transform.cpp
src/QueryPlan/PlanPrinter.cpp
tests/queries/4_cnch_problematic_stateless/40003_bucket_table_join.reference
tests/queries/4_cnch_problematic_stateless/40003_bucket_table_join.sql
tests/queries/4_cnch_stateless/01883_grouping_sets_crash.sql
tests/queries/4_cnch_stateless/46012_optimize_multi_distinct.reference
tests/queries/4_cnch_stateless/46012_optimize_multi_distinct.sql
tests/queries/4_cnch_stateless_no_tenant/40003_bucket_table_join.sql
tests/queries/4_cnch_stateless_no_tenant/46012_optimize_multi_distinct.reference
tests/queries/4_cnch_stateless_no_tenant/48022_explain_analysis.reference
tests/queries/4_cnch_stateless_no_tenant/48022_explain_analysis.sql

* Cherry-pick
* fix: Fix shuffle const null column
* feat: injective function property optimization
* feat: close injective in default
* feat: explain analysis

Daily Cherry-pick from the internal_20230912_151755

---

src/CloudServices/CnchWorkerServiceImpl.cpp
src/Core/Settings.h
src/Storages/MergeTree/MergeTreeDataMergerMutator.cpp
src/Storages/MergeTree/MergeTreeDataPartWriterWide.cpp
src/Storages/StorageCnchMergeTree.cpp
src/WorkerTasks/CloudUniqueMergeTreeMergeTask.cpp
src/WorkerTasks/ManipulationTask.cpp
src/WorkerTasks/ManipulationTask.h
src/WorkerTasks/MergeTreeDataMerger.cpp
tests/queries/4_cnch_stateless/10102_uniquekey_insert_values.sql

fix: unique table merge bug which may leads to duplicated data

---

src/QueryPlan/CreatingSetsStep.cpp

Fix useless repeated lines which should be typo?

Fix useless repeated lines

---

tests/clickhouse-test

- New Feature
- Bug Fix
- Improvement
- Other
...

fix clickhouse-test.py

---

programs/part-toolkit/S3MetaSanitizer.cpp

- Bug Fix
S3MetaSanitizer now support both xml and yaml(it only support xml before)

S3 meta sanitizer tool support yaml

---

src/CloudServices/CnchWorkerServiceImpl.cpp
src/Storages/MergeTree/MergeTreeSettings.h
src/Storages/StorageCnchMergeTree.cpp

Cherry-pick from internal

---

src/Common/ProfileEvents.cpp

Daily cherry-pick from internal

Daily cherry-pick from internal

---

docker/debian/dev-env/Makefile
docker/debian/release/Dockerfile
docker/debian/release/Makefile
docker/debian/release/README.md

- Bug Fix
fix scripte to build image

fix: update release makefile

---

docker/packager/binary/build.sh
docker/packager/packager

modify the packager scripts to avoid prlimit on heavy files.

update packager to avoid prlimit

---

tests/clickhouse-test

- Bug Fix
Fix clickhouse-test script

fix: fix clickhouse-test

---

.github/workflows/ci.yml
docker/ci-deploy/config/daemon-manager.yml
docker/ci-deploy/config/resource-manager.yml
docker/ci-deploy/config/server.yml
docker/ci-deploy/config/tso.yml
docker/ci-deploy/config/worker.yml

- New Feature
Collect coredump file for CI

feat: collect coredump file from CI

---

src/IO/S3Common.cpp
src/Storages/Hive/CnchHiveSettings.h
src/Storages/Hive/DirectoryLister.cpp

This PR fix the issue  #672 
Add virtual_hosted_style setting to Hive Table

fix issue672 add virtual_hosted_style setting to Hive Table

---

README.md

I just corrected several small grammar mistakes in README.md. 
I hereby agree to the terms of the CLA available at: https://github.com/ByConity/ByConity/blob/master/CONTRIBUTING.md
I want contribute more to ByConity. 
Changelog category :
Documentation (changelog entry is not required)

corrected several small grammar mistakes in README.md. 

---

src/Storages/ProjectionsDescription.cpp

fix issue #811 , forbidden add the same dimension columns to  projection to avoid issue 811

Fix issue811, forbidden add the same dimension columns to projection to avoid issue 811

---

doc/ingest_column.md

Add document for ingest column query

doc: Add document for ingest column query

---

src/Client/MultiplexedConnections.cpp
src/DataStreams/RemoteQueryExecutor.cpp

close https://github.com/ByConity/ByConity/issues/821

fix:  No more packets are available

---

docker/docker-compose/docker-compose.multi.yml
docker/docker-compose/docker-compose.multiworkers.yml

fix: docker-compose daemon-manager not found error

---

src/Analyzers/QueryAnalyzer.cpp
src/Core/Settings.h

fix count() choose subcolumn for hive

fix: fix count() choose subcolumn for hive

---

src/Common/HostWithPorts.cpp
src/Common/HostWithPorts.h
src/Common/tests/gtest_host_with_ports.cpp

fix: fix getHostIPFromEnv

---

docker/packager/packager

fix: fix packager

---

src/CloudServices/CnchWorkerServiceImpl.cpp
src/CloudServices/CnchWorkerServiceImpl.h

feat: use threadpool for worker service

feat: use threadpool for worker service

---

docker/test/byconity/Dockerfile
docker/test/byconity/Makefile
docker/test/byconity/clean.sh
docker/test/byconity/process_functional_tests_result.py
docker/test/byconity/run.sh

build byconity-test docker image to test byconity k8s cluster

testing: build byconity-test docker image

---

src/Parsers/ASTGrantQuery.cpp

fix: RBAC remove debug logs

---

src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/DaemonManager/DaemonJobServerBGThread.cpp
src/Storages/System/StorageSystemCnchTables.cpp
tests/queries/4_cnch_stateless_no_tenant/01001_alter_delete.sql

fix: optimization for cnch tables

---

src/Protos/DataModelHelpers.cpp
src/Protos/DataModelHelpers.h
src/Storages/CnchTablePartitionMetricsHelper.cpp
src/Storages/CnchTablePartitionMetricsHelper.h
src/Storages/PartCacheManager.cpp

- Bug Fix
Use scheduleOrThrow (instead of scheduleOrThrowOnError) with a timeout to avoid stuck forever.

fix: resolve task schedule dead lock and improve timeout handling.

---

src/CloudServices/CnchPartGCThread.cpp
src/Common/CurrentMetrics.cpp
src/Core/Settings.h
src/Interpreters/Context.cpp
src/Interpreters/Context.h

- Bug Fix
Use separate scheduling pool for GC tasks.

fix: Use separate scheduling pool for GC tasks.

---

src/Transaction/LockRequest.cpp

- New Feature
- Bug Fix
- Improvement
- Other
...

avoid exception on unlock op

---

src/Common/ResourceMonitor.cpp
src/Common/ResourceMonitor.h

fix: fix the memory collection within the container

---

src/CloudServices/CnchServerServiceImpl.cpp

Fix logic error when checking host server in request redirect.

fix logic error

---

src/Catalog/FDBClient.cpp
src/Catalog/FDBClient.h
src/Catalog/MetastoreFDBImpl.cpp
src/TSO/TSOMetaFDBImpl.h

fix: remove old fdb code

---

src/Storages/MergeTree/GinIndexStore.cpp

- Bug Fix
Fix inverted index didn't insert any data
1. create table test_ivt (key Int, value String, index val_ivt value type inverted(2) granularity 1) engine = CnchMergeTree order by key
2. insert into test_ivt values (0, 'a')

Fix gin index store without any term

---

src/IO/S3Common.cpp

Fixed that the AWS log level could not be set correctly in some cases.

fix: fix aws log level can't be set

---

src/Catalog/IMetastore.cpp

fix logic error in adaptive batch write

---

.github/workflows/ci.yml
tests/queries/skip_list.json

Fix CI test case 00653_verification_monotonic_data_load failed in S3 test suite

fix: fix S3 test suite

---

utils/release-note/release_note_v2.sh

Add release note generator script

chore: add release note generator script

---

utils/create_pr/create_pr.sh

ci: add script to create pr automatically

ci: add script to create pr automatically

---

utils/create_pr/create_pr.sh

ci: fix create_pr script

---

src/Processors/Transforms/FillingTransform.cpp

fix with fill bug

---

.github/workflows/ci.yml
utils/create_pr/create_pr.sh
utils/create_pr/split_pr.sh

ci: add split_pr script

---

.github/workflows/ci.yml
docker/ci-deploy/docker-compose.yml
src/Storages/MergeTree/LateMaterialize/MergeTreeBaseSelectProcessorLM.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeReverseSelectProcessorLM.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeSelectProcessorLM.cpp
src/Storages/MergeTree/MergeTreeBaseSelectProcessor.cpp
src/Storages/MergeTree/MergeTreeBlockReadUtils.cpp
src/Storages/MergeTree/MergeTreeBlockReadUtils.h
src/Storages/MergeTree/MergeTreeReadPool.cpp
src/Storages/MergeTree/MergeTreeReverseSelectProcessor.cpp
src/Storages/MergeTree/MergeTreeSelectProcessor.cpp
src/Storages/MergeTree/MergeTreeThreadSelectBlockInputProcessor.cpp

fix: fix disk cache only cached partial data

fix: fixing disk cache only cached partial data

---

.github/workflows/ci.yml

ci: fix ci

---

src/Common/ProfileEvents.cpp
src/Common/ProfileEvents.h
src/Common/ThreadStatus.h
src/Common/VariableContext.h
src/Interpreters/CnchQueryMetrics/QueryMetricLogHelper.cpp
src/Interpreters/ProcessList.cpp
src/Interpreters/ProcessList.h
src/Interpreters/ProfileEventsExt.cpp
src/Interpreters/ProfileEventsExt.h
src/Interpreters/QueryExchangeLog.h
src/Interpreters/QueryLog.h
src/Interpreters/QueryThreadLog.h
src/Interpreters/ThreadStatusExt.cpp
src/Server/ServerPrometheusMetricsWriter.cpp

perf: remove labelled counters from profile events snapshots

perf: remove labelled counters from profile events snapshots

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/Catalog/MetastoreProxy.cpp
src/Catalog/MetastoreProxy.h
src/Protos/data_models.proto
src/Storages/MergeTree/CnchAttachProcessor.cpp
src/Transaction/CnchServerTransaction.cpp
src/Transaction/TransactionCleaner.cpp
src/Transaction/TransactionCommon.cpp
src/Transaction/TransactionCommon.h

fix: Add undo resource for fs lock

fix: Add undo resource for fs lock

---

programs/server/Server.cpp
src/Common/CurrentMemoryTracker.cpp
src/Common/CurrentMemoryTracker.h
src/Interpreters/DistributedStages/BSPScheduler.cpp
src/Interpreters/DistributedStages/BSPScheduler.h
src/Interpreters/DistributedStages/MPPScheduler.cpp
src/Interpreters/DistributedStages/MPPScheduler.h
src/Interpreters/DistributedStages/Scheduler.cpp
src/Interpreters/DistributedStages/Scheduler.h
src/Interpreters/SegmentScheduler.cpp
src/Interpreters/SegmentScheduler.h

fix: Split scheduler classes into files

fix: Split scheduler classes into files

---

programs/server/Server.cpp
src/Common/CurrentMemoryTracker.cpp
src/Common/CurrentMemoryTracker.h

fix: add untrack memroy for global memory tracker

fix: add untrack memroy for global memory tracker

---

.github/workflows/ci.yml
tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.reference
tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.sh
utils/create_pr/split_pr.sh

test: improve 50010_direct_insert test

test: improve 50010_direct_insert test

---

utils/create_pr/create_pr.sh
utils/create_pr/split_pr.sh

ci: minor fix ci script

---

src/Common/LabelledMetrics.cpp
src/Common/LabelledMetrics.h
src/Common/ProfileEvents.cpp
src/Common/ProfileEvents.h
src/Core/Settings.h
src/Formats/FormatFactory.cpp
src/Formats/FormatSettings.h
src/Interpreters/ProcessList.cpp
src/Interpreters/ThreadStatusExt.cpp
src/Interpreters/executeQuery.cpp
src/Processors/Formats/Impl/CSVRowOutputFormat.cpp
src/Server/ServerPrometheusMetricsWriter.cpp
src/Server/ServerPrometheusMetricsWriter.h
src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/DiskCache/DiskCacheLRU.h
src/Storages/DiskCache/DiskCacheSettings.cpp
src/Storages/DiskCache/DiskCacheSettings.h

fix: compatible settings format_csv_write_utf8_with_bom

fix: compatible settings format_csv_write_utf8_with_bom

---

src/Common/LabelledMetrics.cpp
src/Common/LabelledMetrics.h
src/Common/ProfileEvents.cpp
src/Common/ProfileEvents.h
src/Core/Settings.h
src/Interpreters/ProcessList.cpp
src/Interpreters/ThreadStatusExt.cpp
src/Interpreters/executeQuery.cpp
src/Server/ServerPrometheusMetricsWriter.cpp
src/Server/ServerPrometheusMetricsWriter.h
src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/DiskCache/DiskCacheLRU.h
src/Storages/DiskCache/DiskCacheSettings.cpp
src/Storages/DiskCache/DiskCacheSettings.h

perf: split labelled metrics out of ProfileEvents

perf: split labelled metrics out of ProfileEvents

---

src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/DiskCache/DiskCacheLRU.h
src/Storages/DiskCache/DiskCacheSettings.cpp
src/Storages/DiskCache/DiskCacheSettings.h

fix: support disk cache set throughput limit

fix: support disk cache set throughput limit

---

src/CloudServices/CnchBGThreadsMap.cpp
src/Core/Settings.h
src/Formats/FormatFactory.cpp
src/Formats/FormatSchemaInfo.cpp
src/Functions/FunctionsStringSearch.h
src/Functions/MatchImpl.h
src/Functions/Regexps.h
src/Functions/rlike.cpp
src/Storages/Kafka/StorageCloudKafka.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeRangeReaderLM.cpp
src/Storages/MergeTree/MergeTreeRangeReader.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp
tests/queries/4_cnch_stateless/10120_optimize_query.sql
tests/queries/4_cnch_stateless/13002_rlike_regexp_test.reference
tests/queries/4_cnch_stateless/13002_rlike_regexp_test.sql

fix: Fix mysql function RLIKE

---

src/CloudServices/CnchBGThreadsMap.cpp
src/Core/Settings.h
src/Formats/FormatFactory.cpp
src/Formats/FormatSchemaInfo.cpp
src/Storages/Kafka/StorageCloudKafka.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeRangeReaderLM.cpp
src/Storages/MergeTree/MergeTreeRangeReader.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp
tests/queries/4_cnch_stateless/10120_optimize_query.sql

fix: minor fix for quitting core bg threads

fix: minor fix for quitting core bg threads

---

src/Core/Settings.h
src/Formats/FormatFactory.cpp
src/Formats/FormatSchemaInfo.cpp
src/Storages/Kafka/StorageCloudKafka.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeRangeReaderLM.cpp
src/Storages/MergeTree/MergeTreeRangeReader.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp
tests/queries/4_cnch_stateless/10120_optimize_query.sql

fix: fix 10120_optimize_query

---

src/Core/Settings.h
src/Formats/FormatFactory.cpp
src/Formats/FormatSchemaInfo.cpp
src/Storages/Kafka/StorageCloudKafka.cpp
src/Storages/MergeTree/LateMaterialize/MergeTreeRangeReaderLM.cpp
src/Storages/MergeTree/MergeTreeRangeReader.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp

fix: [cp cnch-dev] fix pb consumption for CnchKafka on cnch-2.0

fix: [cp cnch-dev] fix pb consumption for CnchKafka on cnch-2.0

---

src/Storages/MergeTree/LateMaterialize/MergeTreeRangeReaderLM.cpp
src/Storages/MergeTree/MergeTreeRangeReader.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp

fix: [cnch-dev] fix first filter is const case in combineFilterEqualSize

fix: [cnch-dev] fix first filter is const case in combineFilterEqualSize

---

src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp

feat: replace ListObjects by HeadObject when inserting data to DiskByteS3

feat: replace ListObjects by HeadObject when inserting data to DiskByteS3

---

src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp

fix: rollback interface type change.

fix: rollback interface type change.

---

src/AggregateFunctions/AggregateFunctionQuantile.cpp
src/Analyzers/QueryRewriter.cpp
src/Analyzers/RewriteFusionMerge.cpp
src/Analyzers/RewriteFusionMerge.h
src/Core/AnsiSettings.cpp
src/Interpreters/trySetVirtualWarehouse.cpp
src/Optimizer/QueryUseOptimizerChecker.cpp
src/Storages/StorageCnchMergeTree.cpp
tests/queries/4_cnch_stateless/00273_quantiles.sql
tests/queries/4_cnch_stateless_no_tenant/10020_test_fusion_merge.reference
tests/queries/4_cnch_stateless_no_tenant/10020_test_fusion_merge.sql
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.reference
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.sql
tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.sh

fix: touch active ts for all type tx type

fix: touch active ts for all type tx type

---

src/AggregateFunctions/AggregateFunctionQuantile.cpp
src/Core/AnsiSettings.cpp
tests/queries/4_cnch_stateless/00273_quantiles.sql
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.reference
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.sql
tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.sh

fix: fix quantileTDigestWithSSize

fix: fix quantileTDigestWithSSize

---

src/Core/AnsiSettings.cpp
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.reference
tests/queries/4_cnch_stateless_no_tenant/40038_mix_ansi_settings.sql
tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.sh

fix: dialect type not set join use nulls cnch dev

fix: dialect type not set join use nulls cnch dev

---

tests/queries/4_cnch_stateless_no_tenant/50010_direct_insert.sh

ci: fix 50010_direct_insert

---

src/Interpreters/InterpreterPerfectShard.cpp
src/Optimizer/Rewriter/ColumnPruning.cpp
src/Optimizer/Rewriter/EliminateJoinByForeignKey.cpp
src/Optimizer/Rewriter/GroupByKeysPruning.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rule/Rewrite/MultipleDistinctAggregationToMarkDistinct.cpp
src/Optimizer/Rule/Rewrite/PushAggThroughJoinRules.cpp
src/Optimizer/Rule/Rewrite/PushPartialStepThroughExchangeRules.cpp
src/Optimizer/Rule/Rewrite/SingleDistinctAggregationToGroupBy.cpp
src/Optimizer/Signature/StepNormalizer.cpp
src/Optimizer/tests/gtest_plan_check_correctness.cpp
src/QueryPlan/AggregatingStep.cpp
src/QueryPlan/AggregatingStep.h
src/QueryPlan/Hints/HintsPropagator.cpp
src/QueryPlan/Hints/HintsPropagator.h
src/QueryPlan/Hints/IPlanHint.h
src/QueryPlan/Hints/PushPartialAgg.cpp
src/QueryPlan/Hints/PushPartialAgg.h
src/QueryPlan/Hints/registerHints.cpp
src/QueryPlan/SymbolMapper.cpp
tests/optimizers/correctness/explains/correctness/q20.explain
tests/optimizers/correctness/queries/q20.sql

feat: add push partial agg hint

feat: add push partial agg hint

---

src/CloudServices/CnchMergeMutateThread.cpp
src/Storages/MergeTree/MergeTreeSettings.h

fix: add table-level mutate settings

fix: add table-level mutate settings

---

src/QueryPlan/TableWriteStep.cpp
src/Storages/StorageCnchMergeTree.cpp

fix: fix explain pipeline insert into select

fix: fix explain pipeline insert into select

---

src/Interpreters/GraceHashJoin.cpp
src/Interpreters/GraceHashJoin.h

fix: reduce useless scatter when grace hash join

fix: reduce useless scatter when grace hash join

---

docker/docker-compose/byconity-simple-cluster/server.yml
docker/docker-compose/byconity-simple-cluster/worker.yml

fix: fix docker compose

---

src/CloudServices/CnchServerResource.cpp
src/Common/ProfileEvents.cpp
src/Disks/DiskCacheWrapper.cpp
src/Disks/DiskRestartProxy.cpp
src/Disks/WriteIndirectBufferFromRemoteFS.cpp
src/Disks/WriteIndirectBufferFromRemoteFS.h
src/IO/S3Common.cpp
src/IO/WriteBuffer.h
src/IO/WriteBufferFromByteS3.cpp
src/IO/WriteBufferFromByteS3.h
src/IO/WriteBufferFromFileDecorator.cpp
src/IO/WriteBufferFromFileDecorator.h
src/IO/WriteBufferFromHTTP.cpp
src/IO/WriteBufferFromHTTP.h
src/IO/WriteBufferFromLasfs.cpp
src/IO/WriteBufferFromLasfs.h
src/IO/WriteBufferFromS3.cpp
src/IO/WriteBufferFromS3.h
src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp
src/Server/HTTP/WriteBufferFromHTTPServerResponse.h
src/Server/ServerPrometheusMetricsWriter.h
src/Storages/DataLakes/StorageCnchLas.cpp
src/Storages/HDFS/WriteBufferFromHDFS.cpp
src/Storages/HDFS/WriteBufferFromHDFS.h
src/Storages/Hive/Metastore/JNIHiveMetastore.cpp
src/Storages/Hive/StorageHiveSource.cpp
src/Storages/MergeTree/DeleteBitmapMeta.cpp
src/Storages/MergeTree/IMergeTreeDataPart.cpp
src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp

fix: fix wrong write buffer usage in part dumper

fix: fix wrong write buffer usage in part dumper

---

src/CloudServices/CnchServerResource.cpp
src/Storages/DataLakes/StorageCnchLas.cpp
src/Storages/Hive/Metastore/JNIHiveMetastore.cpp
src/Storages/Hive/StorageHiveSource.cpp

fix: fix las coredump and less data

fix: fix las coredump and less data

---

src/Catalog/DataModelPartWrapper.cpp
src/Catalog/DataModelPartWrapper.h
src/CloudServices/CnchDataWriter.cpp
src/CloudServices/CnchMergeMutateThread.cpp
src/CloudServices/CnchMergeMutateThread.h
src/CloudServices/CnchPartGCThread.cpp
src/Interpreters/ServerPartLog.cpp
src/Interpreters/ServerPartLog.h
src/Protos/DataModelHelpers.cpp
src/Storages/DiskCache/BitmapIndexDiskCacheSegment.cpp
src/Storages/MergeTree/IMergeTreeDataPart.h
src/Storages/StorageCloudMergeTree.cpp
src/Storages/System/StorageSystemCnchParts.cpp
src/Storages/System/StorageSystemCnchStagedParts.cpp
src/Transaction/Actions/DropRangeAction.cpp
src/Transaction/Actions/InsertAction.cpp
src/Transaction/Actions/MergeMutateAction.cpp
src/Transaction/Actions/MergeMutateAction.h
src/Transaction/Actions/S3AttachMetaAction.cpp

feat: enrich server_part_log for better observability

feat: enrich server_part_log for better observability

---

src/Storages/DataLakes/HiveFile/JNIArrowSource.cpp

fix: fix JNIArrowSource build

---

programs/server/Server.cpp
programs/server/Server.h
src/CloudServices/CnchDataWriter.cpp
src/CloudServices/CnchWorkerServiceImpl.cpp
src/Common/HistogramMetrics.h
src/Common/ProfileEvents.cpp
src/Common/ProfileEvents.h
src/Core/Settings.h
src/Interpreters/executeQuery.cpp
src/Storages/DiskCache/BitmapIndexDiskCacheSegment.cpp
src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/DiskCache/DiskCacheLRU.h
src/Storages/DiskCache/FileDiskCacheSegment.cpp
src/Storages/DiskCache/IDiskCache.cpp
src/Storages/DiskCache/IDiskCache.h
src/Storages/DiskCache/MetaFileDiskCacheSegment.cpp
src/Storages/DiskCache/PartFileDiskCacheSegment.cpp
src/Storages/DiskCache/PartFileDiskCacheSegment.h
src/Storages/MergeTree/IMergeTreeDataPart.cpp
src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
src/Storages/MergeTree/MergeTreeIndexReader.cpp
src/Storages/MergeTree/MergeTreeReaderCNCH.cpp
src/Storages/RemoteDiskCacheService.cpp
src/Storages/tests/gtest_remote_cache.cpp
src/benchmark/disk_cache_benchmark.cpp

fix: support mark disk cache load data when disk cache write data

fix: support mark disk cache load data when disk cache write data

---

programs/server/Server.cpp
programs/server/Server.h
src/CloudServices/CnchDataWriter.cpp
src/CloudServices/CnchWorkerServiceImpl.cpp
src/Common/HistogramMetrics.h
src/Common/ProfileEvents.cpp
src/Common/ProfileEvents.h
src/Core/Settings.h
src/Interpreters/executeQuery.cpp
src/Storages/DiskCache/BitmapIndexDiskCacheSegment.cpp
src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/DiskCache/DiskCacheLRU.h
src/Storages/DiskCache/FileDiskCacheSegment.cpp
src/Storages/DiskCache/IDiskCache.cpp
src/Storages/DiskCache/IDiskCache.h
src/Storages/DiskCache/MetaFileDiskCacheSegment.cpp
src/Storages/DiskCache/PartFileDiskCacheSegment.cpp
src/Storages/MergeTree/IMergeTreeDataPart.cpp
src/Storages/MergeTree/MergeTreeCNCHDataDumper.cpp
src/Storages/RemoteDiskCacheService.cpp
src/Storages/tests/gtest_remote_cache.cpp
src/benchmark/disk_cache_benchmark.cpp

fix: support metrics2 for profile event

fix: support metrics2 for profile event

---

src/Core/Settings.h
src/Storages/DiskCache/DiskCacheLRU.cpp
src/Storages/MergeTree/IMergeTreeDataPart.cpp

fix: disk cache support global setting

fix: disk cache support global setting

---

programs/meta-inspector/MetastoreInspector.cpp
src/Core/Settings.h
src/Storages/System/StorageSystemCnchParts.cpp
src/Storages/System/StorageSystemCnchPartsInfo.cpp
src/Storages/System/StorageSystemCnchPartsInfoLocal.cpp
src/Storages/System/StorageSystemCnchTrashItems.cpp
src/Storages/System/StorageSystemCnchTrashItemsInfo.cpp
src/Storages/System/StorageSystemCnchTrashItemsInfoLocal.cpp

fix: expose uuid for system tables.

fix: expose uuid for system tables.

---

src/DataStreams/PushingToViewsBlockOutputStream.cpp
src/DataStreams/PushingToViewsBlockOutputStream.h
src/Functions/map.cpp
src/Storages/MergeTree/CloudMergeTreeBlockOutputStream.cpp

fix: mv push with function cols

fix: mv push with function cols

---

src/Functions/map.cpp

fix: [cp] cnch dev fix getMapKeys with more than 1 millian keys

fix: [cp] cnch dev fix getMapKeys with more than 1 millian keys

---

programs/server/Server.cpp
src/AggregateFunctions/AggregateFunctionBoundingRatio.h
src/Common/Config/VWCustomizedSettings.h
src/Common/tests/gtest_vw_customized_settings.cpp
src/Interpreters/Context.cpp

feat:[cp]vw config auto load

---

src/AggregateFunctions/AggregateFunctionBoundingRatio.h

fix: fix bound ratio incorrect merge cnch dev

fix: fix bound ratio incorrect merge cnch dev

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/README.md
docker/ci-deploy/docker-compose-integration-test.yml
tests/queries/4_cnch_integration/00001_remote_to_community_clickhouse.sql

feat: add nightly integration test

feat: add nightly integration test

---

.github/workflows/nightly_integration_test.yml

fix: nightly integration test

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/docker-compose-integration-test.yml

fix: fix nightly integration test

fix: fix nightly integration test

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/docker-compose-integration-test.yml

fix: github workflow for nightly integration test

fix: github workflow for nightly integration test

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/docker-compose-integration-test.yml

fix: nightly test docker compose

fix: nightly test docker compose

---

.github/workflows/nightly_integration_test.yml

fix: nightly test github work flow

fix: nightly test github work flow

---

.github/workflows/ci.yml
src/Interpreters/DistributedStages/PlanSegment.h
src/Interpreters/DistributedStages/Scheduler.cpp
src/Processors/Exchange/DataTrans/Batch/DiskExchangeDataManager.cpp
src/Processors/Exchange/DataTrans/Brpc/BrpcExchangeReceiverRegistryService.cpp
src/Processors/Exchange/DataTrans/Brpc/BrpcRemoteBroadcastReceiver.cpp
src/Protos/registry.proto
src/QueryPlan/RemoteExchangeSourceStep.cpp
tests/queries/4_cnch_stateless_no_tenant/46001_remove_redundant_distinct.sql
tests/queries/4_cnch_stateless_no_tenant/48016_cte_projection.sql

fix: respect parallel index of map task while registring brpc receivers

fix: respect parallel index of map task while registring brpc receivers

---

src/Catalog/Catalog.cpp
src/Storages/AlterCommands.cpp
src/Storages/MergeTree/MergeTreeDataWriter.cpp
src/Storages/MergeTree/registerStorageMergeTree.cpp
src/Storages/StorageCnchMergeTree.cpp
src/Storages/TTLDescription.cpp
src/Storages/TTLDescription.h
tests/queries/4_cnch_stateless/01007_ttl_create_nullable_date_in_mysql.reference
tests/queries/4_cnch_stateless/01007_ttl_create_nullable_date_in_mysql.sql
tests/queries/4_cnch_stateless/65001_ddl_case_insensitive.reference
tests/queries/4_cnch_stateless/65001_ddl_case_insensitive_upper.reference
tests/queries/4_cnch_stateless_no_tenant/48023_foreign_key_definition.reference

feat: support nullable date type for TTL

feat: support nullable date type for TTL

---

docker/ci-deploy/docker-compose-integration-test.yml
tests/queries/4_cnch_integration/02478_mysql_server_example.reference
tests/queries/4_cnch_integration/02478_mysql_server_example.sh

ci: support test environment for materialized mysql.

ci: support test environment for materialized mysql.

---

docker/ci-deploy/docker-compose-integration-test.yml
tests/queries/4_cnch_integration/02478_mysql_server_example.sh

fix: mysql integration test

---

.github/workflows/ci.yml
.github/workflows/nightly_integration_test.yml

test: fix ci

---

docker/ci-deploy/docker-compose-integration-test.yml

test: fix mysql integration test docker compose

test: fix mysql integration test docker compose

---

docker/ci-deploy/docker-compose-integration-test.yml

test: add health check for mysql db in integration test

test: add health check for mysql db in integration test

---

docker/ci-deploy/docker-compose-integration-test.yml

test: increase start period for healthcheck for mysql in integration test

test: increase start period for healthcheck for mysql in integration test

---

src/DaemonManager/DaemonJobServerBGThread.cpp
src/QueryPlan/SortingStep.cpp
src/QueryPlan/TableScanStep.cpp
src/QueryPlan/TableScanStep.h
src/Storages/DiskCache/PartFileDiskCacheSegment.cpp
src/Storages/MergeTree/Index/BitmapIndexHelper.cpp
src/Storages/MergeTree/Index/BitmapIndexHelper.h
tests/queries/4_cnch_stateless/11009_alter_disk_cache.reference
tests/queries/4_cnch_stateless/11009_alter_disk_cache.sql
tests/queries/4_cnch_stateless/48037_fix_remove_reduntant_sort.sql
tests/queries/skip_list.json

fix: [cp] cnch dev fix disk cache total segments in single compressed block

fix: [cp] cnch dev fix disk cache total segments in single compressed block

---

src/QueryPlan/SortingStep.cpp
src/QueryPlan/TableScanStep.cpp
src/QueryPlan/TableScanStep.h
src/Storages/MergeTree/Index/BitmapIndexHelper.cpp
src/Storages/MergeTree/Index/BitmapIndexHelper.h
tests/queries/4_cnch_stateless/48037_fix_remove_reduntant_sort.sql
tests/queries/skip_list.json

fix: fix jobs concurrency

---

src/QueryPlan/SortingStep.cpp
src/QueryPlan/TableScanStep.cpp
src/QueryPlan/TableScanStep.h
src/Storages/MergeTree/Index/BitmapIndexHelper.cpp
src/Storages/MergeTree/Index/BitmapIndexHelper.h
tests/queries/4_cnch_stateless/48037_fix_remove_reduntant_sort.sql

fix: fix SortingStep proto

---

src/QueryPlan/TableScanStep.cpp
src/QueryPlan/TableScanStep.h
src/Storages/MergeTree/Index/BitmapIndexHelper.cpp
src/Storages/MergeTree/Index/BitmapIndexHelper.h

fix: fix bitmap index function pattern cnch-dev

fix: fix bitmap index function pattern cnch-dev

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/docker-compose-integration-test.yml

test: debug compose integration

test: debug compose integration

---

.github/workflows/nightly_integration_test.yml
docker/ci-deploy/docker-compose-integration-test.yml

test: make mysql db init idempotent

test: make mysql db init idempotent

---

.github/workflows/nightly_integration_test.yml

test: remove debugging sleep

---

src/Core/AnsiSettings.cpp
src/Functions/FunctionBinaryArithmetic.h
src/Processors/Exchange/DataTrans/Batch/DiskExchangeDataManager.cpp
src/Processors/Executors/PipelineExecutor.h
tests/queries/4_cnch_stateless/02015_division_by_zero.sql

feat: add meta inspector command

feat: add meta inspector command

---

src/Core/AnsiSettings.cpp
src/Functions/FunctionBinaryArithmetic.h
src/Processors/Exchange/DataTrans/Batch/DiskExchangeDataManager.cpp
src/Processors/Executors/PipelineExecutor.h
tests/queries/4_cnch_stateless/02015_division_by_zero.sql

fix: catch finish senders in DiskExchangeManager::submitReadTask

fix: catch finish senders in DiskExchangeManager::submitReadTask

---

src/Core/AnsiSettings.cpp
src/Functions/FunctionBinaryArithmetic.h
tests/queries/4_cnch_stateless/02015_division_by_zero.sql

fix: Refactor division by zero and enable for mysql

fix: Refactor division by zero and enable for mysql

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Common/HostWithPorts.h
src/Core/Settings.h
src/DaemonManager/DaemonManager.cpp
src/DataTypes/Serializations/SerializationString.cpp
src/Formats/FormatFactory.cpp
src/Formats/FormatSettings.h
src/Interpreters/Context.cpp
src/Interpreters/Context.h
src/Interpreters/DistributedStages/PlanSegmentSplitter.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/executeQuery.cpp
src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/Optimizer/PlanOptimizer.cpp
src/Optimizer/Rewriter/ColumnPruning.cpp
src/Optimizer/Rewriter/ColumnPruning.h
src/Optimizer/SymbolsExtractor.cpp
src/Optimizer/SymbolsExtractor.h
src/QueryPlan/PlanCache.cpp
src/QueryPlan/QueryPlan.h
src/ResourceManagement/ResourceManager.cpp
src/Storages/Kafka/StorageCloudKafka.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h
src/TSO/TSOServer.cpp
tests/queries/4_cnch_stateless/11016_parse_object_as_string.reference
tests/queries/4_cnch_stateless/11016_parse_object_as_string.sql
tests/queries/4_cnch_stateless_no_tenant/40080_filter_window_to_sorting_limit.reference
tests/queries/4_cnch_stateless_no_tenant/40080_filter_window_to_sorting_limit.sql

fix: pick input_format_json_read_objects_as_strings setting for compatibility

fix: pick input_format_json_read_objects_as_strings setting for compatibility

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Common/HostWithPorts.h
src/Core/Settings.h
src/DaemonManager/DaemonManager.cpp
src/Interpreters/Context.cpp
src/Interpreters/Context.h
src/Interpreters/DistributedStages/PlanSegmentSplitter.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/executeQuery.cpp
src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/Optimizer/PlanOptimizer.cpp
src/Optimizer/Rewriter/ColumnPruning.cpp
src/Optimizer/Rewriter/ColumnPruning.h
src/Optimizer/SymbolsExtractor.cpp
src/Optimizer/SymbolsExtractor.h
src/QueryPlan/PlanCache.cpp
src/QueryPlan/QueryPlan.h
src/ResourceManagement/ResourceManager.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h
src/TSO/TSOServer.cpp
tests/queries/4_cnch_stateless_no_tenant/40080_filter_window_to_sorting_limit.reference
tests/queries/4_cnch_stateless_no_tenant/40080_filter_window_to_sorting_limit.sql

feat: rewrite filter window as sorting limit

feat: rewrite filter window as sorting limit

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Common/HostWithPorts.h
src/DaemonManager/DaemonManager.cpp
src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/ResourceManagement/ResourceManager.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h
src/TSO/TSOServer.cpp

fix: Cron1 cnch dev

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Common/HostWithPorts.h
src/DaemonManager/DaemonManager.cpp
src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/ResourceManagement/ResourceManager.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h
src/TSO/TSOServer.cpp

fix:get consul http host from multi env

fix:get consul http host from multi env

---

src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h

fix: merge version files back to cnch-dev after cnch-2.1 release

fix: merge version files back to cnch-dev after cnch-2.1 release

---

src/Optimizer/MaterializedView/PartitionConsistencyChecker.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h

fix: fix validateAndSyncBaseTablePartitions for query rewrite

fix: fix validateAndSyncBaseTablePartitions for query rewrite

---

src/Core/Settings.h
src/Interpreters/ConcurrentHashJoin.cpp
src/Interpreters/ConcurrentHashJoin.h
src/Interpreters/ExpressionAnalyzer.cpp
src/Interpreters/join_common.cpp
src/Optimizer/Property/PropertyDeterminer.cpp
src/Processors/QueryPipeline.cpp
src/Processors/Transforms/JoiningTransform.cpp
src/Processors/Transforms/JoiningTransform.h
src/QueryPlan/JoinStep.cpp
src/Storages/Hive/HivePartition.cpp
src/Storages/Hive/HivePartition.h
src/Storages/MaterializedView/PartitionTransformer.cpp
src/Storages/StorageMaterializedView.cpp
tests/queries/4_cnch_stateless_no_tenant/48037_convert_lc_nullable_to_nullable.sql

feat: support state function no shuffle

feat: support state function no shuffle

---

src/Core/Settings.h
src/Interpreters/ConcurrentHashJoin.cpp
src/Interpreters/ConcurrentHashJoin.h
src/Interpreters/ExpressionAnalyzer.cpp
src/Interpreters/join_common.cpp
src/Processors/QueryPipeline.cpp
src/Processors/Transforms/JoiningTransform.cpp
src/Processors/Transforms/JoiningTransform.h
src/QueryPlan/JoinStep.cpp
src/Storages/Hive/HivePartition.cpp
src/Storages/Hive/HivePartition.h
src/Storages/MaterializedView/PartitionTransformer.cpp
src/Storages/StorageMaterializedView.cpp
tests/queries/4_cnch_stateless_no_tenant/48037_convert_lc_nullable_to_nullable.sql

fix: fix_nullable_lc_convert_to_nullable

fix: fix_nullable_lc_convert_to_nullable

---

src/Core/Settings.h
src/Interpreters/ConcurrentHashJoin.cpp
src/Interpreters/ConcurrentHashJoin.h
src/Interpreters/ExpressionAnalyzer.cpp
src/Processors/QueryPipeline.cpp
src/Processors/Transforms/JoiningTransform.cpp
src/Processors/Transforms/JoiningTransform.h
src/QueryPlan/JoinStep.cpp
src/Storages/Hive/HivePartition.cpp
src/Storages/Hive/HivePartition.h
src/Storages/MaterializedView/PartitionTransformer.cpp
src/Storages/StorageMaterializedView.cpp

feat: pick ConcurrentHashJoin optimization

feat: pick ConcurrentHashJoin optimization

---

src/Core/Settings.h
src/Storages/Hive/HivePartition.cpp
src/Storages/Hive/HivePartition.h
src/Storages/MaterializedView/PartitionTransformer.cpp
src/Storages/StorageMaterializedView.cpp

fix: Fix hive table access and add enable_async_mv_debug setting

fix: Fix hive table access and add enable_async_mv_debug setting

---

src/Catalog/Catalog.cpp
src/Catalog/MetastoreProxy.cpp
src/Catalog/MetastoreProxy.h
src/CloudServices/CnchServerServiceImpl.cpp

fix: add partition info to KV when seeing new staged part.

fix: add partition info to KV when seeing new staged part.

---

src/Functions/elt.cpp
src/Processors/Transforms/WindowTransform.cpp

feat: Support nullable columns in functions

feat: Support nullable columns in functions

---

src/Core/Settings.h
src/Functions/elt.cpp
src/Processors/Transforms/JoiningTransform.cpp
src/Processors/Transforms/JoiningTransform.h
src/Processors/Transforms/WindowTransform.cpp

fix: remove unused setting & refine code

fix: remove unused setting & refine code

---

docker/ci-deploy/docker-compose.yml

ci: use multi write-workers.

---

docker/ci-deploy/docker-compose.yml

ci: use 2 write workers in CI

---

.github/workflows/release.yml
cliff.toml
docker/debian/release/Makefile
docker/packager/packager

Add an GitHub action for auto release.
ci: Add an GitHub action for auto release.

Add an GitHub action for auto release.

---

utils/create_pr/create_pr.sh
utils/create_pr/proc_title.sh
utils/create_pr/proc_title_test.sh

Update existing MR comments sanity check rules to better link with Github rules:
- if the MR comments contain Github keywords like `Closes #1217`, it should be included
- if  the MR comments contain merge request/pull request from internal branches, they should be masked/ignored
- if the MR comments reference to internal branches, they should be masked/ignored
- if  the MR comments links point to internal urls, they should be ignored

update filter rules on mr titles to migrate internal mrs to external

---

.github/workflows/ci.yml
src/Interpreters/DistributedStages/Scheduler.cpp
src/Processors/Exchange/DataTrans/MultiPathReceiver.cpp
src/QueryPlan/RemoteExchangeSourceStep.cpp
tests/queries/4_cnch_stateless_no_tenant/46001_remove_redundant_distinct.sql
tests/queries/4_cnch_stateless_no_tenant/48016_cte_projection.sql
tests/queries/4_cnch_stateless_no_tenant/48016_execute_uncorrelated_subquery_first.sql

fix: support shared cte in bsp mode

fix: support shared cte in bsp mode

---

src/CloudServices/CnchMergeMutateThread.cpp
src/Common/SettingsChanges.cpp
src/Databases/DatabaseCnch.cpp
src/Interpreters/InterpreterCreateWorkerGroupQuery.cpp
src/Optimizer/Property/PropertyDeterminer.cpp
src/Parsers/ASTCreateWorkerGroupQuery.cpp
src/Parsers/ASTCreateWorkerGroupQuery.h
src/Parsers/ParserCreateWorkerGroupQuery.cpp
src/QueryPlan/GraphvizPrinter.cpp
src/ResourceManagement/ResourceManagerClient.cpp
src/ResourceManagement/ResourceManagerClient.h
src/ResourceManagement/ResourceManagerController.cpp
src/ResourceManagement/ResourceManagerController.h
src/ResourceManagement/ResourceManagerServiceImpl.cpp
src/ResourceManagement/WorkerGroupManager.cpp
src/ResourceManagement/WorkerGroupManager.h
src/ResourceManagement/WorkerGroupResourceCoordinator.cpp
src/Storages/StorageCnchMergeTree.cpp
tests/queries/4_cnch_stateless/01001_alter_vw.sql
tests/queries/4_cnch_stateless_no_tenant/48035_insert_select_no_gather.reference
tests/queries/4_cnch_stateless_no_tenant/48035_insert_select_no_gather.sql

fix: no need gather in insert select

fix: no need gather in insert select

---

src/CloudServices/CnchMergeMutateThread.cpp
src/Common/SettingsChanges.cpp
src/Databases/DatabaseCnch.cpp
src/Interpreters/InterpreterCreateWorkerGroupQuery.cpp
src/Parsers/ASTCreateWorkerGroupQuery.cpp
src/Parsers/ASTCreateWorkerGroupQuery.h
src/Parsers/ParserCreateWorkerGroupQuery.cpp
src/ResourceManagement/ResourceManagerClient.cpp
src/ResourceManagement/ResourceManagerClient.h
src/ResourceManagement/ResourceManagerController.cpp
src/ResourceManagement/ResourceManagerController.h
src/ResourceManagement/ResourceManagerServiceImpl.cpp
src/ResourceManagement/WorkerGroupManager.cpp
src/ResourceManagement/WorkerGroupManager.h
src/ResourceManagement/WorkerGroupResourceCoordinator.cpp
src/Storages/StorageCnchMergeTree.cpp
tests/queries/4_cnch_stateless/01001_alter_vw.sql

fix: minor updates for cnch

---

utils/create_pr/proc_title.sh

chore: fix util script

---

src/Core/Settings.h
src/Functions/JSONPath/Generator/IObjectJSONGenerator.h
src/Functions/JSONPath/Generator/IObjectJSONVisitor.h
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/executeQuery.cpp
src/Optimizer/Property/PropertyDeterminer.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/Processors/Executors/PullingPipelineExecutor.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
src/Server/TCPHandler.cpp
src/Server/TCPHandler.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql
tests/queries/4_cnch_stateless/11009_alter_disk_cache.sql

fix:Fix compile warning

---

src/Core/Settings.h
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/executeQuery.cpp
src/Optimizer/Property/PropertyDeterminer.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/Processors/Executors/PullingPipelineExecutor.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
src/Server/TCPHandler.cpp
src/Server/TCPHandler.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql
tests/queries/4_cnch_stateless/11009_alter_disk_cache.sql

feat: enable retry by default

---

src/Core/Settings.h
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Interpreters/InterpreterSelectQueryUseOptimizer.cpp
src/Interpreters/executeQuery.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/Processors/Executors/PullingPipelineExecutor.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
src/Server/TCPHandler.cpp
src/Server/TCPHandler.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql

perf: fix perf regressions under high concurrency

perf: fix perf regressions under high concurrency

---

src/Core/Settings.h
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/Processors/Executors/PullingPipelineExecutor.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
src/Server/TCPHandler.cpp
src/Server/TCPHandler.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql

feat: introduce use_sync_pipeline_executor

feat: introduce use_sync_pipeline_executor

---

src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql

fix: fix write rows/bytes in query log

fix: fix write rows/bytes in query log

---

src/Optimizer/Rewriter/UnifyNullableType.cpp
src/Optimizer/Rewriter/UnifyNullableType.h
src/QueryPlan/WindowStep.cpp
src/QueryPlan/WindowStep.h
tests/optimizers/correctness/explains/correctness/q18.explain
tests/queries/4_cnch_stateless/00441_nulls_in.sql
tests/queries/4_cnch_stateless/09020_late_materialize_array_join.sql

fix: force UnifyNullableVisitor visit all plan nodes

fix: force UnifyNullableVisitor visit all plan nodes

---

src/mysqlxx/CMakeLists.txt
src/mysqlxx/Pool.cpp
src/mysqlxx/Pool.h
tests/integration/test_mysql_database_engine/test.py

fix: Fix mysql pool memory leak

fix: Fix mysql pool memory leak

---

src/Access/SaslClient.cpp
src/Access/SaslClient.h
src/MergeTreeCommon/MergeTreeMetaBase.cpp
src/MergeTreeCommon/MergeTreeMetaBase.h
src/MergeTreeCommon/assignCnchParts.cpp
src/MergeTreeCommon/assignCnchParts.h
src/Optimizer/CardinalityEstimate/FilterEstimator.cpp
src/Optimizer/CardinalityEstimate/FilterEstimator.h
src/Optimizer/Cascades/Task.cpp
src/Optimizer/ExpressionInterpreter.cpp
src/Optimizer/ExpressionInterpreter.h
src/Optimizer/ExpressionUtils.cpp
src/Optimizer/ExpressionUtils.h
src/Optimizer/LiteralEncoder.cpp
src/Optimizer/LiteralEncoder.h
src/Optimizer/PredicateUtils.cpp
src/Optimizer/PredicateUtils.h
src/Optimizer/Property/Property.cpp
src/Optimizer/Property/Property.h
src/Optimizer/Property/PropertyDeriver.cpp
src/Optimizer/Property/PropertyDeterminer.cpp
src/Optimizer/Rule/Rewrite/PushIntoTableScanRules.cpp
src/Storages/IStorage.cpp
src/Storages/IStorage.h
src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp
src/Storages/StorageDistributed.cpp
src/Storages/StorageDistributed.h
tests/queries/4_cnch_stateless_no_tenant/48032_active_prewhere.reference

fix: fix sasl callback context setup

fix: fix sasl callback context setup

---

src/MergeTreeCommon/MergeTreeMetaBase.cpp
src/MergeTreeCommon/MergeTreeMetaBase.h
src/Optimizer/CardinalityEstimate/FilterEstimator.cpp
src/Optimizer/CardinalityEstimate/FilterEstimator.h
src/Optimizer/ExpressionInterpreter.cpp
src/Optimizer/ExpressionInterpreter.h
src/Optimizer/LiteralEncoder.cpp
src/Optimizer/LiteralEncoder.h
src/Optimizer/PredicateUtils.cpp
src/Optimizer/PredicateUtils.h
src/Optimizer/Rule/Rewrite/PushIntoTableScanRules.cpp
src/Storages/IStorage.cpp
src/Storages/IStorage.h
src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp
src/Storages/StorageDistributed.cpp
src/Storages/StorageDistributed.h
tests/queries/4_cnch_stateless_no_tenant/48032_active_prewhere.reference

fix: move pushFilterIntoStorage into IStorage

fix: move pushFilterIntoStorage into IStorage

---

src/Access/AccessControlManager.cpp
src/Access/AccessControlManager.h
src/Access/ContextAccess.cpp
src/Access/ContextAccess.h
src/Access/KVAccessStorage.cpp
src/Access/KVAccessStorage.h
src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/CloudServices/CnchMergeMutateThread.cpp
src/Common/ErrorCodes.cpp
src/Common/ProfileEvents.cpp
src/Disks/IO/AsynchronousBoundedReadBuffer.cpp
src/Disks/IO/ThreadPoolRemoteFSReader.cpp
src/Interpreters/Context.cpp
src/QueryPlan/ReadFromMergeTree.cpp
src/Storages/Hive/StorageCloudHive.cpp
src/Storages/Hive/StorageHiveSource.cpp
src/Storages/Hive/StorageHiveSource.h
src/Storages/MergeTree/MergeTreeCloudData.cpp
src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
src/Storages/MergeTree/MergeTreeThreadSelectBlockInputProcessor.cpp
src/Storages/MergeTree/MergeTreeThreadSelectBlockInputProcessor.h

feat: Add more profile events and log to diagnose async reading

feat: Add more profile events and log to diagnose async reading

---

src/Access/AccessControlManager.cpp
src/Access/AccessControlManager.h
src/Access/ContextAccess.cpp
src/Access/ContextAccess.h
src/Access/KVAccessStorage.cpp
src/Access/KVAccessStorage.h
src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/CloudServices/CnchMergeMutateThread.cpp
src/Common/ErrorCodes.cpp
src/Interpreters/Context.cpp
src/Storages/Hive/StorageCloudHive.cpp
src/Storages/Hive/StorageHiveSource.cpp
src/Storages/Hive/StorageHiveSource.h

feat: KV Rbac performance optimization for granting lots of query to one user. Also fix a coredump and dead lock

feat: KV Rbac performance optimization for granting lots of query to one user. Also fix a coredump and dead lock

---

src/CloudServices/CnchMergeMutateThread.cpp
src/Storages/Hive/StorageCloudHive.cpp
src/Storages/Hive/StorageHiveSource.cpp
src/Storages/Hive/StorageHiveSource.h

fix: fix reading partition col without row count

fix: fix reading partition col without row count

---

src/CloudServices/CnchMergeMutateThread.cpp

fix: use commitV2() to release txn

fix: use commitV2() to release txn

---

src/Optimizer/MaterializedView/MaterializedViewStructure.cpp
src/Optimizer/Rewriter/MaterializedViewRewriter.cpp
src/QueryPlan/JoinStep.cpp
src/QueryPlan/JoinStep.h
src/QueryPlan/PlanSymbolReallocator.h

fix: udpate libhdfs3 version to support read hdfs files within the same idc

fix: udpate libhdfs3 version to support read hdfs files within the same idc

---

src/Optimizer/MaterializedView/MaterializedViewStructure.cpp
src/Optimizer/Rewriter/MaterializedViewRewriter.cpp
src/QueryPlan/JoinStep.cpp
src/QueryPlan/JoinStep.h
src/QueryPlan/PlanSymbolReallocator.h

fix: fix for materialized view union rewrite

fix: fix for materialized view union rewrite

---

utils/create_pr/split_pr.sh

chore: fix utils script

---

src/Functions/extractTimeZoneFromFunctionArguments.cpp

feat: remove empty timezone check

feat: remove empty timezone check

---

src/CloudServices/CnchRefreshMaterializedViewThread.cpp
src/CloudServices/CnchRefreshMaterializedViewThread.h
src/Core/SettingsEnums.cpp
src/Core/SettingsEnums.h
src/Interpreters/InterpreterCreateQuery.cpp
src/Interpreters/InterpreterRefreshQuery.cpp
src/Interpreters/trySetVirtualWarehouse.cpp
src/Parsers/formatTenantDatabaseName.cpp
src/Parsers/formatTenantDatabaseName.h
src/Storages/IStorage.cpp
src/Storages/MaterializedView/ApplyPartitionFilterVisitor.cpp
src/Storages/MaterializedView/ApplyPartitionFilterVisitor.h
src/Storages/MaterializedView/PartitionTransformer.cpp
src/Storages/MaterializedView/ViewRefreshTaskLog.cpp
src/Storages/MaterializedView/ViewRefreshTaskLog.h
src/Storages/StorageMaterializedView.cpp
src/Storages/StorageMaterializedView.h

fix: fix refresh empty database, vw settings, tenant id

fix: fix refresh empty database, vw settings, tenant id

---

src/Storages/MaterializedView/MaterializedViewVersionedPartCache.h
src/Storages/StorageMaterializedView.cpp

fix: fix mv version part meta cache weight

fix: fix mv version part meta cache weight

---

base/common/bthread_exception.cpp
src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/CloudServices/CnchDataWriter.cpp
src/CloudServices/CnchDedupHelper.cpp
src/MergeTreeCommon/MergeTreeMetaBase.cpp
src/MergeTreeCommon/MergeTreeMetaBase.h
src/Storages/IStorage.h
src/Storages/MergeTree/CloudMergeTreeBlockOutputStream.cpp
src/Storages/MergeTree/CnchAttachProcessor.cpp
src/Storages/MergeTree/CnchAttachProcessor.h
src/Storages/StorageCloudMergeTree.h
src/Storages/StorageCnchMergeTree.cpp

fix: fix alloc-dealloc-mismatch

fix: fix alloc-dealloc-mismatch

---

src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/CloudServices/CnchDataWriter.cpp
src/CloudServices/CnchDedupHelper.cpp
src/MergeTreeCommon/MergeTreeMetaBase.cpp
src/MergeTreeCommon/MergeTreeMetaBase.h
src/Storages/IStorage.h
src/Storages/MergeTree/CloudMergeTreeBlockOutputStream.cpp
src/Storages/MergeTree/CnchAttachProcessor.cpp
src/Storages/MergeTree/CnchAttachProcessor.h
src/Storages/StorageCloudMergeTree.h
src/Storages/StorageCnchMergeTree.cpp

fix: uuid empty bug for undo buffer

fix: uuid empty bug for undo buffer

---

src/Storages/StorageView.cpp
src/Storages/StorageView.h
src/Storages/System/StorageSystemDatabases.cpp
src/Storages/System/StorageSystemDatabases.h

fix: fix pushdown map-key to view

fix: fix pushdown map-key to view

---

src/Storages/System/StorageSystemDatabases.cpp
src/Storages/System/StorageSystemDatabases.h

fix: tenant should not see DBs create by default user

fix: tenant should not see DBs create by default user

---

src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/Storages/CnchTablePartitionMetrics.cpp
src/Storages/CnchTablePartitionMetrics.h
src/Storages/CnchTablePartitionMetricsHelper.cpp

fix: push down aggregation op to metastore.

fix: push down aggregation op to metastore.

---

.github/workflows/release.yml

release disk space after pushing docker.
release disk space after pushing docker.

ci: release disk space after pushing docker.

---

src/Common/StorageElection/StorageElector.cpp
src/Server/HTTP/HTTPServerConnection.cpp

fix: leader election improve

---

src/Catalog/Catalog.h
src/Interpreters/DatabaseCatalog.cpp
src/Interpreters/DatabaseCatalog.h
src/ServiceDiscovery/ServiceDiscoveryConsul.cpp
src/Storages/StorageMaterializedView.cpp
src/Storages/System/StorageSystemDatabases.cpp
src/Storages/System/StorageSystemDatabases.h
src/Storages/System/StorageSystemTables.cpp

feat: support GC empty partition

feat: support GC empty partition

---

src/Catalog/Catalog.h
src/Interpreters/DatabaseCatalog.cpp
src/Interpreters/DatabaseCatalog.h
src/ServiceDiscovery/ServiceDiscoveryConsul.cpp
src/Storages/System/StorageSystemDatabases.cpp
src/Storages/System/StorageSystemDatabases.h
src/Storages/System/StorageSystemTables.cpp

feat: Reduction in the use of ListObject in DiskByteS3

feat: Reduction in the use of ListObject in DiskByteS3

---

src/Catalog/Catalog.h
src/Interpreters/DatabaseCatalog.cpp
src/Interpreters/DatabaseCatalog.h
src/ServiceDiscovery/ServiceDiscoveryConsul.cpp
src/Storages/System/StorageSystemDatabases.cpp
src/Storages/System/StorageSystemDatabases.h
src/Storages/System/StorageSystemTables.cpp

fix: fix rbac check with wrong database name

fix: fix rbac check with wrong database name

---

src/Catalog/Catalog.h
src/ServiceDiscovery/ServiceDiscoveryConsul.cpp

fix: fix compilation error

---

src/Interpreters/InterpreterAlterQuery.cpp
src/Interpreters/InterpreterCreateQuery.cpp
src/Interpreters/InterpreterExplainQuery.cpp
src/Interpreters/InterpreterShowPreparedStatementQuery.cpp
src/Interpreters/MySQL/InterpretersAnalyticalMySQLDDLQuery.cpp
src/Interpreters/ProcessorProfile.cpp
src/Interpreters/ProcessorProfile.h
src/Optimizer/tests/gtest_base_materialized_view_test.h
src/Optimizer/tests/gtest_base_plan_test.cpp
src/Parsers/ParserCreateQuery.h
src/Processors/Transforms/ExplainAnalyzeTransform.cpp
src/QueryPlan/PlanPrinter.cpp
src/QueryPlan/PlanPrinter.h
src/ResourceGroup/IResourceGroupManager.cpp
src/Storages/AlterCommands.cpp
src/Storages/AlterCommands.h
tests/queries/4_cnch_stateless/41832_show_nullable_types_ansi.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.sql
tests/queries/4_cnch_stateless_no_tenant/46010_explain_with_settings.reference

fix: optimize explain info

---

src/Interpreters/InterpreterAlterQuery.cpp
src/Interpreters/InterpreterCreateQuery.cpp
src/Interpreters/MySQL/InterpretersAnalyticalMySQLDDLQuery.cpp
src/Parsers/ParserCreateQuery.h
src/ResourceGroup/IResourceGroupManager.cpp
src/Storages/AlterCommands.cpp
src/Storages/AlterCommands.h
tests/queries/4_cnch_stateless/41832_show_nullable_types_ansi.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.sql

fix: Change alter test name

---

src/Interpreters/InterpreterAlterQuery.cpp
src/Interpreters/InterpreterCreateQuery.cpp
src/Interpreters/MySQL/InterpretersAnalyticalMySQLDDLQuery.cpp
src/Parsers/ParserCreateQuery.h
src/ResourceGroup/IResourceGroupManager.cpp
src/Storages/AlterCommands.cpp
src/Storages/AlterCommands.h
tests/queries/4_cnch_stateless/41832_show_nullable_types_ansi.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.reference
tests/queries/4_cnch_stateless/60010_mysql_ddl_alter.sql

feat: make columns nullable by default under mysql

feat: make columns nullable by default under mysql

---

src/Common/tests/gtest_utils.cpp
src/Optimizer/Cascades/CascadesOptimizer.cpp
src/Optimizer/Cascades/CascadesOptimizer.h
tests/queries/4_cnch_stateless_no_tenant/45013_cache_policy.reference
tests/queries/4_cnch_stateless_no_tenant/45013_cache_policy.sql

fix: fix explain cost for tests

fix: fix explain cost for tests

---

src/Optimizer/Cascades/CascadesOptimizer.cpp
src/Optimizer/Cascades/CascadesOptimizer.h

fix: fix WorkerSizeFinder for CascadesOptimizer

fix: fix WorkerSizeFinder for CascadesOptimizer

---

src/Core/Settings.h
src/Processors/Transforms/SquashingChunksTransform.cpp
src/Processors/Transforms/SquashingChunksTransform.h
src/QueryPlan/TableWriteStep.cpp
src/QueryPlan/TableWriteStep.h
src/Storages/StorageCloudMergeTree.h
src/Storages/StorageCnchMergeTree.h
tests/queries/4_cnch_stateless/00278_insert_already_sorted.sql
tests/queries/4_cnch_stateless/09006_late_materialize_nested.sql

fix: fix insert select can not parallel on non-unique table

fix: fix insert select can not parallel on non-unique table

---

src/Catalog/Catalog.cpp

fix: remove useless get delete bitmap request for non-unique table

fix: remove useless get delete bitmap request for non-unique table

---

src/Functions/FunctionsHashing.cpp
src/Functions/FunctionsHashing.h
src/Processors/Exchange/RepartitionTransform.h
src/Processors/tests/gtest_exchange_transform.cpp
src/Processors/tests/gtest_processers_utils.cpp
tests/queries/4_cnch_stateless_no_tenant/48037_tealimit_ansi.sql

feat: Merge branch 'exchange_nullable_mr' into 'cnch-dev'

feat: Merge branch 'exchange_nullable_mr' into 'cnch-dev'

---

utils/create_pr/split_pr.sh

ci: fix utils script

---

tests/queries/4_cnch_stateless/50001_test_query_cache_non_transactional.sql

fix: fix unstable test

---

utils/create_pr/collect_megoo.sh

chore: adding script to collect megoo

chore: adding script to collect megoo

---

src/Interpreters/DistributedStages/BSPScheduler.cpp
src/Interpreters/DistributedStages/PlanSegmentExecutor.cpp
src/Interpreters/DistributedStages/PlanSegmentManagerRpcService.cpp
src/Interpreters/DistributedStages/Scheduler.cpp
src/Interpreters/SegmentScheduler.cpp
src/Interpreters/sendPlanSegment.cpp
utils/create_pr/collect_megoo.sh
utils/create_pr/collect_megoo_byconity.sh

fix: add key log to help user know the procedure

fix: add key log to help user know the procedure

---

programs/meta-inspector/MetastoreInspector.cpp
src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/Catalog/CatalogUtils.h
src/Catalog/MetastoreByteKVImpl.cpp
src/Catalog/MetastoreCommon.h
src/Catalog/MetastoreProxy.cpp
src/Catalog/MetastoreProxy.h
src/CloudServices/CnchPartGCThread.cpp
src/CloudServices/CnchPartGCThread.h
src/Common/ScanWaitFreeMap.h
src/Common/tests/gtest_scan_wait_free_map.cpp
src/Functions/FunctionsJSON.h
src/Protos/data_models.proto
src/Storages/CnchPartitionInfo.h
src/Storages/CnchTablePartitionMetricsHelper.cpp
src/Storages/MergeTree/MergeTreeSettings.h
src/Storages/PartCacheManager.cpp
src/Storages/PartCacheManager.h
src/Storages/TableMetaEntry.cpp
src/Storages/TableMetaEntry.h
src/Storages/tests/gtest_part_storage_cache.cpp
tests/queries/4_cnch_stateless/00918_json_functions.reference
tests/queries/4_cnch_stateless/00918_json_functions.sql
tests/queries/4_cnch_stateless/00918_json_functions_type_object.reference
tests/queries/4_cnch_stateless/00918_json_functions_type_object.sql

fix: fix cache inconsistency issues

fix: fix cache inconsistency issues

---

src/Catalog/Catalog.cpp
src/Common/tests/gtest_scan_wait_free_map.cpp
src/Functions/FunctionsJSON.h
tests/queries/4_cnch_stateless/00918_json_functions.reference
tests/queries/4_cnch_stateless/00918_json_functions.sql
tests/queries/4_cnch_stateless/00918_json_functions_type_object.reference
tests/queries/4_cnch_stateless/00918_json_functions_type_object.sql

feat: Add filtered parts info to getServerDataPartsInPartitions and add ScanWaitFreeMap.Atomic test

feat: Add filtered parts info to getServerDataPartsInPartitions and add ScanWaitFreeMap.Atomic test

---

src/Functions/FunctionsJSON.h
tests/queries/4_cnch_stateless/00918_json_functions.reference
tests/queries/4_cnch_stateless/00918_json_functions.sql
tests/queries/4_cnch_stateless/00918_json_functions_type_object.reference
tests/queries/4_cnch_stateless/00918_json_functions_type_object.sql

feat: cnch dev JSONExtract support map type

feat: cnch dev JSONExtract support map type

---

.github/workflows/ci.yml

run ci for release branch

---

src/Interpreters/Context.cpp
src/Optimizer/EqualityInference.cpp
src/Optimizer/EqualityInference.h
src/Optimizer/PlanOptimizer.cpp
src/Optimizer/Rewriter/PredicatePushdown.cpp
src/Optimizer/Rewriter/PredicatePushdown.h
src/Optimizer/UnwrapCastInComparison.cpp
src/Storages/PartCacheManager.h
tests/optimizers/tpcds/explains/tpcds100/q11.explain
tests/optimizers/tpcds/explains/tpcds100/q14.explain
tests/optimizers/tpcds/explains/tpcds100/q4.explain
tests/optimizers/tpcds/explains/tpcds1000/q11.explain
tests/optimizers/tpcds/explains/tpcds1000/q14.explain
tests/optimizers/tpcds/explains/tpcds1000/q4.explain
tests/optimizers/tpcds/explains/tpcds1000_not_show_stats/q11.explain
tests/optimizers/tpcds/explains/tpcds1000_not_show_stats/q14.explain
tests/optimizers/tpcds/explains/tpcds1000_not_show_stats/q4.explain
tests/optimizers/tpcds/explains/tpcds1000_sample/q11.explain
tests/optimizers/tpcds/explains/tpcds1000_sample/q14.explain
tests/optimizers/tpcds/explains/tpcds1000_sample/q4.explain
tests/queries/4_cnch_stateless_no_tenant/40088_fix_share_common_expression_with_rf.reference
tests/queries/4_cnch_stateless_no_tenant/48024_add_required_property_in_set.reference
tests/queries/4_cnch_stateless_no_tenant/48025_remove_redundant_union.reference

fix:fix predicate pushdown ineffective bug

fix:fix predicate pushdown ineffective bug

---

src/Interpreters/Context.cpp
src/Storages/PartCacheManager.h

fix: fix compilation

---

.github/workflows/ci.yml
tests/clickhouse-test

test: support multi-server for clickhouse-test

test: support multi-server for clickhouse-test

---

docker/test/byconity/run.sh

testing: improve test image

---

programs/server/Server.cpp
src/Optimizer/ExpressionInterpreter.cpp
src/Optimizer/ExpressionInterpreter.h
src/Parsers/ExpressionElementParsers.cpp
src/Storages/TTLDescription.cpp
tests/queries/4_cnch_stateless_no_tenant/40070_better_constant_folding.reference
tests/queries/4_cnch_stateless_no_tenant/40070_better_constant_folding.sql
tests/queries/4_cnch_stateless_no_tenant/45007_ip_stats.reference

fix: not do constant folding for complex literals cnch dev

fix: not do constant folding for complex literals cnch dev

---

programs/server/Server.cpp
src/Parsers/ExpressionElementParsers.cpp
src/Storages/TTLDescription.cpp

fix: update cnch metrics init and support ttl move where

fix: update cnch metrics init and support ttl move where

---

src/Catalog/Catalog.cpp
src/Catalog/Catalog.h
src/Catalog/MetastoreProxy.cpp
src/Catalog/MetastoreProxy.h
src/CloudServices/CnchServerClient.cpp
src/CloudServices/CnchServerClient.h
src/CloudServices/CnchServerServiceImpl.cpp
src/CloudServices/CnchServerServiceImpl.h
src/Core/Settings.h
src/Protos/cnch_server_rpc.proto
src/Protos/data_models.proto
src/Storages/PartCacheManager.cpp
src/Storages/PartCacheManager.h
src/Storages/TableMetaEntry.h

feat: proactively create table meta when creating table.

feat: proactively create table meta when creating table.

---

src/Interpreters/DistributedStages/PlanSegmentManagerRpcService.cpp
src/Interpreters/DistributedStages/Scheduler.cpp
src/Interpreters/DistributedStages/Scheduler.h

fix: fix bsp scheduler queries hung

fix: fix bsp scheduler queries hung

---

src/Optimizer/Rewriter/ColumnPruning.cpp
tests/queries/0_stateless/48034_fix_distinct_to_agg.sql

fix: fix distinct to agg

---

.github/workflows/release.yml
docker/debian/release/Makefile
docker/packager/packager

ci: add action for auto release.

---

src/Core/Settings.h
src/Interpreters/InterpreterInsertQuery.cpp
src/Parsers/ASTInsertQuery.h
src/Parsers/ParserInsertQuery.cpp
src/Parsers/ParserInsertQuery.h
src/Processors/Exchange/DataTrans/RpcChannelPool.cpp
src/Transaction/CnchLock.cpp
src/Transaction/LockManager.cpp
tests/queries/4_cnch_stateless/60107_mysql_dml_replace.reference
tests/queries/4_cnch_stateless/60107_mysql_dml_replace.sql

feat: Add parser logic for REPLACE INTO

feat: Add parser logic for REPLACE INTO

---

src/Core/Settings.h
src/Processors/Exchange/DataTrans/RpcChannelPool.cpp
src/Transaction/CnchLock.cpp
src/Transaction/LockManager.cpp

fix: fix connection reuse

---

src/Core/Settings.h
src/Transaction/CnchLock.cpp
src/Transaction/LockManager.cpp

fix: [cp]lock bugs

---

.github/workflows/ci.yml
unittest.sh

feat: redirect unit test stderr to stdout

feat: redirect unit test stderr to stdout

---

docker/ci-deploy/docker-compose-s3.yml

ci: fix unstable s3 ci

---

src/Optimizer/Rewriter/BitmapIndexSplitter.cpp
src/Optimizer/Rewriter/BitmapIndexSplitter.h
src/Optimizer/Rule/Rewrite/PushProjectionRules.cpp
src/Storages/HDFS/HDFSFileSystem.cpp
src/Storages/IStorage.cpp
src/Storages/MergeTree/ChecksumsCache.h
src/Storages/MergeTree/IMergeTreeDataPart.cpp
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.reference
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.sql

fix: [cp] Does not change server_vw_name for IStorage::renameInMemory to avoid affected by QueryAnalyzer etc

fix: [cp] Does not change server_vw_name for IStorage::renameInMemory to avoid affected by QueryAnalyzer etc

---

src/Optimizer/Rewriter/BitmapIndexSplitter.cpp
src/Optimizer/Rewriter/BitmapIndexSplitter.h
src/Optimizer/Rule/Rewrite/PushProjectionRules.cpp
src/Storages/HDFS/HDFSFileSystem.cpp
src/Storages/MergeTree/ChecksumsCache.h
src/Storages/MergeTree/IMergeTreeDataPart.cpp
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.reference
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.sql

fix: cnch dev remove unnecessary getChecksums calls in loadDataParts

fix: cnch dev remove unnecessary getChecksums calls in loadDataParts

---

src/Optimizer/Rewriter/BitmapIndexSplitter.cpp
src/Optimizer/Rewriter/BitmapIndexSplitter.h
src/Optimizer/Rule/Rewrite/PushProjectionRules.cpp
src/Storages/HDFS/HDFSFileSystem.cpp
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.reference
tests/queries/4_cnch_stateless_no_tenant/48028_only_push_bitmap_with_index.sql

fix: Fix bitmap index check

---

src/Interpreters/HashJoin.cpp

fix: [cnch] follow up join_blk_split

fix: [cnch] follow up join_blk_split

---

docker/debian/release/Makefile
docker/packager/binary/build.sh

fix bin dir inside the docker.
fix bin dir inside the docker.

ci: fix bin dir inside the docker.

---

tests/queries/4_cnch_stateless_no_tenant/48037_tealimit_ansi.sql

ci(clickhousech@m-3877853060): fix 48037_tealimit_ansi unstable case.

Cherry-pick hotfixes for 0.4.x

---

src/CloudServices/CnchMergeMutateThread.cpp

Patch for transaction->commitV2();

Merge 'cherry-pick-9c63e6e5' into 'cnch-2.1'

---

.github/workflows/ci.yml
src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp

GIN store will following mvcc part chain to find the correct part with index store
fix #1812

fix #1812: gin store will lookup correct part by following mvcc part chain

---

docker/CI/multi-servers/server.yml
docker/CI/s3/server.yml
docker/ci-deploy/config/daemon-manager.yml
docker/ci-deploy/config_for_s3_storage/daemon-manager.yml
docker/docker-compose/byconity-multi-cluster/daemon-manager.yml
docker/docker-compose/byconity-multiworkers-cluster/daemon-manager.yml
docker/docker-compose/byconity-simple-cluster/daemon-manager.yml
docker/docker-compose/byconity-simple-cluster/server.yml
docker/docker-compose/byconity-simple-cluster/worker.yml
src/ServiceDiscovery/ServiceDiscoveryLocal.cpp

- New Feature
- Bug Fix
- Improvement
- Other
...

Cp hot fix

---

.gitmodules

I hereby agree to the terms of the CLA available at:
- Bug Fix
fix typo in .gitmodules

fix typo in .gitmodules
