src/Core/Settings.h
- Settings
...
- Bypass db lock by default, better distributed lock server needs to wait for the implementation of distributed lock
...
=> bypass db lock when creating table by default

src/Storages/MergeTree/MergeTreeRangeReader.cpp
Remove some outdated logic of bitmap index
=> Remove outdated logic in range reader

src/Disks/HDFS/DiskByteHDFS.cpp, src/IO/ReadSettings.h, src/Storages/MergeTree/MergeTreeMarksLoader.cpp, src/Storages/MergeTree/MergeTreeReaderStream.cpp
- Bug Fix
remove buffer size assertion during loading marks, solve issue #80 
...
The buffer size is not always equals to file size due the use of pread and read_all_once set to false in `ReadBufferFromByteHDFS`.  `hdfsPRead` may return the buffer size less than the requested read size even if eof is not reach. `ReadBufferFromByteHDFS` will shrink the working buffer in this case.
...
If you are doing this for the first time, it's recommended to read the lightweight [Contributing to ByConity Documentation](https://github.com/ByConity/ByConity/blob/master/CON …
=> Remove buffer size assertion during loading marks

src/DaemonManager/DaemonManager.cpp
- New Feature
- Bug Fix
- Improvement
- Other
...
...
=> revert code that disable PartClustering in DM

src/Databases/DatabaseCnch.cpp, src/Databases/DatabaseCnch.h, src/Interpreters/DatabaseCatalog.cpp
- Remove short-cut to get table via UUID in database catalog, it cannot use storage cache and has bad effect on performance
- Add query-level storage cache (in DatabaseCnch) to reduce calls to kv 
...
=> Add query-level storage cache

src/CloudServices/CnchMergeMutateThread.cpp, src/CloudServices/CnchMergeMutateThread.h, src/CloudServices/CnchWorkerClientPools.cpp, src/CloudServices/CnchWorkerClientPools.h, src/CloudServices/DedupWorkerManager.cpp, src/CloudServices/DedupWorkerManager.h, src/Interpreters/VirtualWarehouseHandle.cpp, src/Interpreters/VirtualWarehouseHandle.h, src/Interpreters/WorkerGroupHandle.cpp, src/Interpreters/WorkerGroupHandle.h, src/ResourceManagement/ResourceTracker.cpp, src/Storages/Kafka/CnchKafkaConsumeManager.h, src/Storages/Kafka/CnchKafkaConsumerScheduler.cpp, src/Storages/Kafka/CnchKafkaConsumerScheduler.h, src/TableFunctions/TableFunctionCnch.cpp
- Improvement
- Use VirtualWarehousePool as the only way for getting workers.
- Fix divide zero error for ResourceTracker
=> Use VW pool as the only way for getting clients

src/Disks/DiskHelpers.cpp
- Bug Fix
Fixes https://github.com/ByConity/ByConity/issues/154. When the process go into background the `stderr` is closed. Hence the fmt can't write to this stderr. It throw exception
```
2023.03.31 11:40:11.517116 [ 2444357 ] {9dbe212d-5708-4884-aa68-7c716f30b340} <Error> TCPHandler: Code: 1001, e.displayText() = DB::Exception: fmt::v7::system_error: cannot write to file: Input/output error SQLSTATE: HY000, Stack trace:
0. /data01/minh.dao/git/cnch-ce-merge/ClickHouse/contrib/libcxx/include/exception:133: std::runtime_error::runtime_error(char const*) @ 0x19301170 in /data01/minh.dao/git/cnch-ce-merge/ClickHouse/build/programs/clickhouse
1. /data01/minh.dao/git/cnch-ce-merge/ClickHouse/contrib/fmtlib-cmake/../fmtlib/include/fmt/format.h:3000: fmt::v7::system_error::system_error<>(int, …
```
=> fix fmt cannot write to file

contrib/libhdfs3-open-cmake/CMakeLists.txt
- Improvement
old kernels (< 3.17) don't have SYS_getrandom. Always use POSIX implementation to have better compatibility
fix: #210
=> old kernel hdfs support

src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp, src/Storages/MergeTree/MergeTreeDataPartCNCH.h
- Bug Fix
implement calculate column size for MergeTreeDataPartCNCH
...
=> fix: add calculate column sizes

contrib/libhdfs3-open-cmake/CMakeLists.txt, src/Access/CMakeLists.txt, src/Access/KerberosInit.cpp, src/Access/KerberosInit.h, src/Access/examples/CMakeLists.txt, src/Access/examples/Kerberos_init.cpp, src/Common/config.h.in, src/Storages/CMakeLists.txt, src/Storages/HDFS/HDFSAuth.cpp, src/Storages/HDFS/HDFSAuth.h, src/Storages/HDFS/HDFSCommon.h, src/Storages/HDFS/HDFSFileSystem.cpp, src/Storages/HDFS/examples/CMakeLists.txt, src/Storages/HDFS/examples/Hdfs_krb5.cpp
- New Feature
add krb5 support for hdfs
add conf in server.xml in <yandex></yandex>
<hadoop_kerberos_keytab>/path/to/keytab</hadoop_kerberos_keytab>
<hadoop_kerberos_principal>kerberos_principal</hadoop_kerberos_principal>
<hadoop_security_kerberos_ticket_cache_path>/ticket/cache/path</hadoop_security_kerberos_ticket_cache_path>
add conf in hdfs3.xml like 
<property>
<name>hadoop.security.authentication</name>
<value>KERBEROS</value>
</property>
<property>
<name>dfs.use.internal.credential.format</name>
<value>false</value>
</property>
<property>
<name>dfs.data.transfer.protection</name>
<value>authentication</value>
</property>
<property>
<name>dfs.block.access.token.enable</name>
<value>true</value>
</property>
=> support krb5 for hdfs

programs/server/Server.cpp, src/Common/ProfileEvents.cpp, src/Interpreters/Context.cpp, src/Interpreters/Context.h, src/MergeTreeCommon/MergeTreeMetaBase.cpp, src/MergeTreeCommon/MergeTreeMetaBase.h, src/Storages/MergeTree/IMergeTreeDataPart.cpp, src/Storages/MergeTree/IMergeTreeDataPart.h, src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp, src/Storages/MergeTree/MergeTreeDataPartCNCH.h, src/Storages/PrimaryIndex.h, src/Storages/PrimaryIndexCache.h
-  Cache hot primary key index in memory.
Trying to solve https://github.com/ByConity/ByConity/issues/205
=> In-memory cache for primary key index

contrib/udns-cmake/CMakeLists.txt, programs/server/Server.cpp
- Bug Fix
When ByConity is deployed in k8s, the service discovery module will work in `dns` mode. It didn't use the DNS server address specify in `/etc/resolv.conf`. The reason because in udns library is build with `HAVE_CONFIG_H` flags disabled. So i fix the way the library is built by updating `CMakeLists.txt` file
I also removed some dead code
=> fix: dns service discovery mode not work in k8s

src/CloudServices/CnchServerServiceImpl.cpp, src/Core/Settings.h, src/DataStreams/BlockIO.cpp, src/DataStreams/BlockIO.h, src/Interpreters/executeQuery.cpp, src/Interpreters/executeQuery.h, src/Transaction/TransactionCoordinatorRcCnch.cpp
- New Feature
- Auto forwarding sql to host server when having multiple servers in order to utilize the metadata cache. By default, it is disabled, you need to set `enable_auto_query_forwarding=1` to enable it.
- Close https://github.com/ByConity/ByConity/issues/248 and release as a preview(experiment) feature in GA release.
- The design is https://github.com/ByConity/ByConity/issues/208
=> auto forward query to host server when having multiple servers

src/MergeTreeCommon/CnchTopologyMaster.cpp, src/MergeTreeCommon/CnchTopologyMaster.h
- Bug Fix
Any application code that acquire Context lock in the scope of BackgroundSchedulePool can cause hang when shutdown.
Explaination:
In the shutdown function of the context
the mutex is acquire first then it start to shutdown BackgroundSchedulePool members.
If the thread that managed by BackgroundSchedulePool is acquire that mutex again. For example like this Topology fetcher
It will causing dead lock
The stacktrace of those two thread here
```
#0  0x00007f0b2e6c1f7c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f0b2e6bbbb5 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000000000b310336 in pthread_mutex_lock (arg=0x7f0b2c4410a8) at /data01/minh.dao/git/ByConity/src/Common/ThreadFuzzer.cpp:268
#3  0x00000000192a10a9 in …
```
=> fix: fix hang when shutdown

base/libbiginteger/README.md, src/Optimizer/Rule/Rewrite/InlineProjections.cpp
cherry pick below from `cnch-ce-merge`:
```
commit 199eeddf11f922565a7a5bac2c5e9ac7ac81d207
Merge: 65972948db7 108e2cbbfb3
Date:   Thu Jan 5 13:50:46 2023 +0000
Merge branch 'fix-big-integer-readme' into 'cnch-ce-merge'
fix(clickhosuech@0000): Keep the BigInteger orignal README
See merge request dp/ClickHouse!10251
```
=> cp: 199eedd

src/IO/S3Common.cpp, src/IO/S3Common.h
- Bug Fix
Add a new configuration to allow use path style or virtual host style when access s3, since some service only allow use virtual host style
add a new configuration in storage_configuration.disks.{some_disk}.virtual_host_style, it can be set to true or false, default is false, which use path style, set it to true to use virtual host style
example are
```
<storage_configuration>
<disks>
<server_s3_disk0>
<virtual_host_style>true</virtual_host_style>
... some other field ...
</server_s3_disk0>
... some other field ...
</disks>
... some other field ...
</storage_configuration>
```
=> Export s3's virtual host style config

.github/workflows/ci.yml
- Improvement
- NDEBUG is always defined in bprc and Enable Debug
=> fix TaskGroup::current_task() returns task control in debug mode

src/Catalog/FDBClient.cpp, src/Catalog/FDBClient.h, src/Catalog/MetastoreFDBImpl.h
- Bug Fix
Fix #384
Non optimal fix for transaction timeout issue. We create new transaction for read instead of using old transaction. The implementation inspired from https://github.com/apple/foundationdb/blob/main/bindings/python/fdb/locality.py
=> fix: fix #384

CMakeLists.txt, cmake/build_info.cmake
Currently for k8s deployment, is it not easy to find out which version the deployment contains. In this PR I will add a build info file into output of the build. This file latter will be added into docker image. Hence we login into the docker image, we can view this file for build information
=> package Improvement: add build info file into output of the build

src/Access/KerberosInit.cpp, src/Access/KerberosInit.h, src/Storages/HDFS/HDFSAuth.cpp, src/Storages/HDFS/HDFSAuth.h
add kinit timeout to renew credentials.
default kinit timeout is 30min
add <hadoop_security_kerberos_kinit_timeout> in your server and worker config
```
<hadoop_security_kerberos_kinit_timeout>1800</hadoop_security_kerberos_kinit_timeout>
```
https://github.com/ByConity/ByConity/issues/591
=> add kinit timeout for runKinit

src/WorkerTasks/ManipulationList.cpp
- Bug Fix
Merge branch 'zema/cnch-2.0-fixNullMemoryTrackerInRpc' into 'cnch-ce-merge'
fix(clickhousech@m-15056756): check CurrentThread memory tracker not null
See merge request dp/ClickHouse!15779
=> fix: check CurrentThread memory tracker not null

src/Storages/Hive/HiveFile/HiveORCFile.cpp
- New Feature
- Bug Fix
- Improvement
- Other
fix:  Constructing **arrow_column_to_ch_column** object should use **ORC** parameters instead of **Parquet** parameters in the getReader method of **HiveORCFile.cpp**
=> fix: hive orc file bug, should use orc not parquet

src/Catalog/FDBClient.cpp
- Bug Fix
FDB re-create transaction if transaction is too old when scanning
=> Recreate transaction if transaction too old when scan

src/IO/WriteBufferFromFile.h
Sync on finalize  may cause slow writes to the tmp part.
from https://github.com/ByConity/ByConity/commit/cae95d5a02c428644bca173b4b742b5eda140424
=> revert WriteBufferFromFile change

programs/server/Server.cpp, src/Access/AccessControlManager.cpp, src/Interpreters/Context.cpp
- Bug Fix
- Init KVStorage later in Server.cpp to prevent null pointer acesses
- getLock in setUser after logging in as AccessControlManager has long running IO ops. This is to prevent deadlocks
=> Init KVStorage and getLock later

src/Common/PoolBase.h
when timeout equal zero, std::condition_variable will return immediately【lock will not unlock】, this  will lead to connectionpool deadlock. This will fix issue #787
=> fix connectionpool deadlock

src/Interpreters/VirtualWarehouseHandle.cpp
When using the Kafka engine in LeastConsumers and Hash mode, newly added workers will not be utilized unless the server is restarted.
=> fix: fix getAllWorkers&getWorkerByHash not update work list

src/CloudServices/CnchWorkerClient.cpp, src/Core/Settings.h
- New Feature
Add a parameter to control the brpc timeout for data parts
#881
=> feat: add brpc_data_parts_timeout_ms parameters to control part data sending timeout

src/Catalog/MetastoreCommon.h, src/Catalog/MetastoreProxy.cpp
There was a bug we noticed when Daemon manager was trying to clean up a lot of transactions:
```
2023.11.22 14:06:22.057689 [ 6659 ] {} <Error> TxnGCThread: Error occurs during daemon TxnGCThread execution: Code: 2101, e.displayText() = DB::Exception: FDB error : Transaction exceeds byte limit SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1e26f752 in /opt/byconity/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xd4d4200 in /opt/byconity/bin/clickhouse
2. DB::Catalog::MetastoreFDBImpl::check_fdb_op(int const&) @ …
```
=> fix too many bytes error on fdb batch write

src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp
threre are too many error message in s3 partition remove logic:
1. try remove directory first
2. if directory is empty,  ends successfully
3. if directory is not empty, print error message , fallback to normal recursive remove
step 3 should print info message instead of error message
this will fix #917
=> change log level from error to info when remove not empty directory partition remove

src/DaemonManager/DaemonJobGlobalGC.cpp
We spent a lot of hours to find why garbage collection was not happening due to missing info logs.
=> add more useful info logs about fail reason in dm gc thread

src/QueryPlan/TableWriteStep.cpp, src/Storages/StorageCnchMergeTree.cpp
fix: add lru cache for invert index to avoid oom AND disable String to Array(XXX) CAST at ddl modify column Scenario
=> fix: add lru cache for invert index to avoid oom AND disable String to Array(XXX) CAST at ddl modify column Scenario

src/DataStreams/PushingToViewsBlockOutputStream.cpp, src/DataStreams/PushingToViewsBlockOutputStream.h, src/Functions/map.cpp, src/Storages/MergeTree/CloudMergeTreeBlockOutputStream.cpp, src/Storages/StorageCnchMergeTree.cpp, tests/queries/4_cnch_stateless/01001_alter_drop_partition.reference, tests/queries/4_cnch_stateless/01001_alter_drop_partition.sql
fix: throw exception when DROP PARTITION WHERE contains no partition key
=> fix: throw exception when DROP PARTITION WHERE contains no partition key

utils/create_pr/create_pr.sh
chore: fix util script
`create_pr.sh` script execute failed when executed from directories different than the directory contains the script
=> chore: fix util script

src/Storages/MergeTree/MergeTreeWhereOptimizer.cpp
fix: some functions can not push into prewhere
=> fix: some functions can not push into prewhere

src/Storages/HDFS/WriteBufferFromHDFS.cpp
fix: fix hdfsCloseFile() can be called twice if encounter error
=> fix: fix hdfsCloseFile() can be called twice if encounter error

src/CloudServices/CnchPartGCThread.cpp
fix: [cp] skip bad ttl when doing partition gc
=> fix: [cp] skip bad ttl when doing partition gc

.github/workflows/ci.yml, src/Storages/MergeTree/MergeTreeDataPartCNCH.cpp, src/Storages/StorageCnchMergeTree.cpp, unittest.sh
fix: skip column size check for mutation & swallow the exception when submitting mutation
=> fix: skip column size check for mutation & swallow the exception when submitting mutation

src/Storages/HDFS/HDFSFileSystem.cpp
fix: use nnproxy access to replace nameservice style hdfs url
=> fix: use nnproxy access to replace nameservice style hdfs url

src/Optimizer/Rewriter/BitmapIndexSplitter.cpp, src/Optimizer/Rule/Rewrite/PushProjectionRules.cpp
fix: only push bitmapindex column to tablescan
=> fix: only push bitmapindex column to tablescan

src/Common/ChineseTokenExtractor.cpp
- Bug Fix https://github.com/ByConity/ByConity/issues/1654
Fix Chinese Tokenizer for like filter with '%' end
For Using Chinese Tokenizer Inverted index , the inner '%' of like string is ignored and assumed as a token in string.
=> fix Chinese Tokenizer with like filter token

src/Disks/DiskByteS3.cpp, src/Disks/DiskByteS3.h, src/FormaterTool/PartWriter.cpp, src/IO/S3Common.cpp, src/IO/S3Common.h
Fix S3 segment upload file part file size cannot be configured.
Added parameters' max_single.part_upload_size 'and' min_upload_part_size '
https://github.com/ByConity/ByConity/issues/1679
- Improvement
Fix S3 segment upload file part file size cannot be configured.
Added parameters' max_single.part_upload_size 'and' min_upload_part_size '
...
=> Fix S3 segment upload file part file size cannot be configured

tests/queries/4_cnch_stateless/40057_ansi_nullify_grouping.sql
Ansi nullify grouping test uses TTL 1 year for rows, which stales now. Removing such unnecessary TTL will make the test case more robust.
=> fix unit test failure from ansi_nullify_grouping.sql
